// Code generated by qtc from "propfind.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line propfind.qtpl:1
package templates

//line propfind.qtpl:1
import (
	"net/http"
	"net/url"
	"os"
)

//line propfind.qtpl:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line propfind.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line propfind.qtpl:9
func StreamPropfindBegin(qw422016 *qt422016.Writer) {
//line propfind.qtpl:9
	qw422016.N().S(`<?xml version="1.0" encoding="UTF-8"?><D:multistatus xmlns:D="DAV:">`)
//line propfind.qtpl:12
}

//line propfind.qtpl:12
func WritePropfindBegin(qq422016 qtio422016.Writer) {
//line propfind.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line propfind.qtpl:12
	StreamPropfindBegin(qw422016)
//line propfind.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line propfind.qtpl:12
}

//line propfind.qtpl:12
func PropfindBegin() string {
//line propfind.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line propfind.qtpl:12
	WritePropfindBegin(qb422016)
//line propfind.qtpl:12
	qs422016 := string(qb422016.B)
//line propfind.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line propfind.qtpl:12
	return qs422016
//line propfind.qtpl:12
}

//line propfind.qtpl:14
func StreamPropfindEnd(qw422016 *qt422016.Writer) {
//line propfind.qtpl:14
	qw422016.N().S(`</D:multistatus>`)
//line propfind.qtpl:16
}

//line propfind.qtpl:16
func WritePropfindEnd(qq422016 qtio422016.Writer) {
//line propfind.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line propfind.qtpl:16
	StreamPropfindEnd(qw422016)
//line propfind.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line propfind.qtpl:16
}

//line propfind.qtpl:16
func PropfindEnd() string {
//line propfind.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line propfind.qtpl:16
	WritePropfindEnd(qb422016)
//line propfind.qtpl:16
	qs422016 := string(qb422016.B)
//line propfind.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line propfind.qtpl:16
	return qs422016
//line propfind.qtpl:16
}

//line propfind.qtpl:18
func StreamPropfindItemOKResponse(qw422016 *qt422016.Writer, name string, fi os.FileInfo, enableContentTypeProbe bool) {
//line propfind.qtpl:18
	qw422016.N().S(`<D:response><D:href>`)
//line propfind.qtpl:20
	qw422016.N().S((&url.URL{Path: name}).EscapedPath())
//line propfind.qtpl:20
	qw422016.N().S(`</D:href>`)
//line propfind.qtpl:25
	qw422016.N().S(`<D:propstat><D:prop><D:resourcetype>`)
//line propfind.qtpl:28
	if fi.IsDir() {
//line propfind.qtpl:28
		qw422016.N().S(`<D:collection />`)
//line propfind.qtpl:28
	}
//line propfind.qtpl:28
	qw422016.N().S(`</D:resourcetype>`)
//line propfind.qtpl:29
	if !fi.IsDir() {
//line propfind.qtpl:29
		qw422016.N().S(`<D:getcontenttype>`)
//line propfind.qtpl:31
		if enableContentTypeProbe {
//line propfind.qtpl:32
			qw422016.E().S(fileContentType(name))
//line propfind.qtpl:33
		} else {
//line propfind.qtpl:33
			qw422016.N().S(`application/octet-stream`)
//line propfind.qtpl:35
		}
//line propfind.qtpl:35
		qw422016.N().S(`</D:getcontenttype><D:getcontentlength>`)
//line propfind.qtpl:37
		qw422016.N().DL(fi.Size())
//line propfind.qtpl:37
		qw422016.N().S(`</D:getcontentlength>`)
//line propfind.qtpl:38
	}
//line propfind.qtpl:38
	qw422016.N().S(`<D:displayname>`)
//line propfind.qtpl:39
	qw422016.E().S(fileDisplayName(name))
//line propfind.qtpl:39
	qw422016.N().S(`</D:displayname><D:getlastmodified>`)
//line propfind.qtpl:40
	qw422016.N().S(fi.ModTime().UTC().Format(http.TimeFormat))
//line propfind.qtpl:40
	qw422016.N().S(`</D:getlastmodified></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response>`)
//line propfind.qtpl:45
}

//line propfind.qtpl:45
func WritePropfindItemOKResponse(qq422016 qtio422016.Writer, name string, fi os.FileInfo, enableContentTypeProbe bool) {
//line propfind.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
//line propfind.qtpl:45
	StreamPropfindItemOKResponse(qw422016, name, fi, enableContentTypeProbe)
//line propfind.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line propfind.qtpl:45
}

//line propfind.qtpl:45
func PropfindItemOKResponse(name string, fi os.FileInfo, enableContentTypeProbe bool) string {
//line propfind.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
//line propfind.qtpl:45
	WritePropfindItemOKResponse(qb422016, name, fi, enableContentTypeProbe)
//line propfind.qtpl:45
	qs422016 := string(qb422016.B)
//line propfind.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
//line propfind.qtpl:45
	return qs422016
//line propfind.qtpl:45
}

//line propfind.qtpl:47
func StreamPropfindItemBadResponse(qw422016 *qt422016.Writer, name string, str string) {
//line propfind.qtpl:47
	qw422016.N().S(`<D:response><D:href>`)
//line propfind.qtpl:49
	qw422016.N().U(name)
//line propfind.qtpl:49
	qw422016.N().S(`</D:href><D:propstat><D:status>`)
//line propfind.qtpl:51
	qw422016.E().S(str)
//line propfind.qtpl:51
	qw422016.N().S(`</D:status></D:propstat></D:response>`)
//line propfind.qtpl:54
}

//line propfind.qtpl:54
func WritePropfindItemBadResponse(qq422016 qtio422016.Writer, name string, str string) {
//line propfind.qtpl:54
	qw422016 := qt422016.AcquireWriter(qq422016)
//line propfind.qtpl:54
	StreamPropfindItemBadResponse(qw422016, name, str)
//line propfind.qtpl:54
	qt422016.ReleaseWriter(qw422016)
//line propfind.qtpl:54
}

//line propfind.qtpl:54
func PropfindItemBadResponse(name string, str string) string {
//line propfind.qtpl:54
	qb422016 := qt422016.AcquireByteBuffer()
//line propfind.qtpl:54
	WritePropfindItemBadResponse(qb422016, name, str)
//line propfind.qtpl:54
	qs422016 := string(qb422016.B)
//line propfind.qtpl:54
	qt422016.ReleaseByteBuffer(qb422016)
//line propfind.qtpl:54
	return qs422016
//line propfind.qtpl:54
}
