[Listener]
Network = "tcp" # "tcp" or "unix"

# tcp: address
# unix: unix socket path
Address = ":20001"

[Listener.TLS]
Enable = false

# WSFS-Core will load tls key pair to memory when start listening, Please
# reload server after renew
#CertFile = "/path/to/cert"
#KeyFile = "/path/to/key"

[Webdav]
Enable = true

# If disable, wsfs will set "application/octet-stream" as HTTP Header
# "Content-Type". In this way, most browser will no try display file but just
# donwload it.
#EnableContentTypeProbe = true

# For debug currently, not recommand use in production.
#AllowPropfindInfDepth = false

[Webdav.Webui]
Enable = true

# If enable, webui will show filesystem reported dir size
#ShowDirSize = false

# Place /path/to/custom/custom.js or/and /path/to/custom/custom.css and 
# uncomment this to custom webui. Note that you can access file
# /path/to/custom/FILENAME by url /custom/FILENAME?webui-assets. If changed,
# please reload server.
#CustomResources = "/path/to/custom"

#[WSFS]
#Enable = true

[Anonymous]
Enable = false

[[Storages]]
Id = "main"
Path = "/mnt/wsfs"

[[Users]]
Name = "test"
Storage = "main"
SecretHash = "$2a$10$pkBmWN2U0W8ddGLQBOfHS.K/G6I6/m5KxVt6l4atyhMcxPKEwFWci" # test
