#Uid=1000
#Gid=1000
#OtherUid=0
#OtherGid=0

[Listener]
Network = "tcp"
Address = ":20001"

[TLS]
Enable = false
#CertFile = "/path/to/cert"
#KeyFile = "/path/to/key"

[Webdav]
Enable = true
EnableContentTypeProbe = true
AllowPropfindInfDepth = true

[Webdav.Webui]
Enable = true
ShowDirSize = false

[Anonymous]
Enable = false

[[Storages]]
Id = "main"
Path = "/mnt/wsfs"

[[Users]]
Name = "test"
Storage = "main"
SecretHash = "$2a$10$pkBmWN2U0W8ddGLQBOfHS.K/G6I6/m5KxVt6l4atyhMcxPKEwFWci" # test
