# WSFS-Core will use the first element of this header as the remote address.
# Empty means using the connection info. (default)
#RealIpHeader = ""

# The `Server` header that WSFS-Core sends in responses.
# Empty means `WSFS/<version>`. (default)
#ServerHeader = ""

[Listener]
Network = "tcp" # "tcp" or "unix"

# tcp: address
# unix: unix socket path
Address = ":20001"

[Listener.TLS]
Enable = false

# WSFS-Core loads the TLS key pair into memory when it starts listening.
# Reload the server after renewing certificates.
#CertFile = "/path/to/cert"
#KeyFile = "/path/to/key"

[Webdav]
Enable = true

# If disabled, WSFS-Core will set the HTTP `Content-Type` header to
# `application/octet-stream`. In this case, most browsers will download files
# instead of trying to display them.
#EnableContentTypeProbe = true

# For debugging only; not recommended for production use.
#AllowPropfindInfDepth = false

[Webdav.Webui]
Enable = true

# If enabled, WebUI will show filesystem-reported directory sizes.
#ShowDirSize = false

# Place `/path/to/custom/custom.js` and/or `/path/to/custom/custom.css`, then
# uncomment this to customize WebUI. Files under `/path/to/custom/FILENAME`
# are accessible via `/custom/FILENAME?webui-assets`. Reload the server after
# changes.
#CustomResources = "/path/to/custom"

#[WSFS]
#Enable = true

[Anonymous]
Enable = false

[[Storages]]
Id = "main"
Path = "/mnt/wsfs"

[[Users]]
Name = "test"
Storage = "main"
SecretHash = "$2a$10$pkBmWN2U0W8ddGLQBOfHS.K/G6I6/m5KxVt6l4atyhMcxPKEwFWci" # test
