// Code generated by 'genCommandCalls.go'. DO NOT EDIT.
package wsfs

import (
	"io"
	"wsfs-core/internal/share/wsfsprotocol"
)

func (s *session) doCommandCall(clientMark, cmd uint8, r io.Reader) {
	switch cmd {
	case wsfsprotocol.CmdOpen:
		var req wsfsprotocol.CmdOpenStruct
		err := wsfsprotocol.ReadCmdOpenStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdOpen(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdClose:
		var req wsfsprotocol.CmdCloseStruct
		err := wsfsprotocol.ReadCmdCloseStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdClose(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdRead:
		var req wsfsprotocol.CmdReadStruct
		err := wsfsprotocol.ReadCmdReadStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdRead(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdReadDir:
		var req wsfsprotocol.CmdReadDirStruct
		err := wsfsprotocol.ReadCmdReadDirStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdReadDir(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdReadLink:
		var req wsfsprotocol.CmdReadLinkStruct
		err := wsfsprotocol.ReadCmdReadLinkStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdReadLink(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdWrite:
		var req wsfsprotocol.CmdWriteStruct
		dataBuf := s.acquireFastBuffer()
		err := wsfsprotocol.ReadCmdWriteStructFromReaderWithBuffer(&req, r, dataBuf)
		if err != nil {
			s.releaseFastBuffer(dataBuf)
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			defer s.releaseFastBuffer(dataBuf)
			s.cmdWrite(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdSeek:
		var req wsfsprotocol.CmdSeekStruct
		err := wsfsprotocol.ReadCmdSeekStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdSeek(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdAllocate:
		var req wsfsprotocol.CmdAllocateStruct
		err := wsfsprotocol.ReadCmdAllocateStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdAllocate(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdGetAttr:
		var req wsfsprotocol.CmdGetAttrStruct
		err := wsfsprotocol.ReadCmdGetAttrStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdGetAttr(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdSetAttr:
		var req wsfsprotocol.CmdSetAttrStruct
		err := wsfsprotocol.ReadCmdSetAttrStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdSetAttr(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdSync:
		var req wsfsprotocol.CmdSyncStruct
		err := wsfsprotocol.ReadCmdSyncStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdSync(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdMkdir:
		var req wsfsprotocol.CmdMkdirStruct
		err := wsfsprotocol.ReadCmdMkdirStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdMkdir(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdSymLink:
		var req wsfsprotocol.CmdSymLinkStruct
		err := wsfsprotocol.ReadCmdSymLinkStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdSymLink(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdRemove:
		var req wsfsprotocol.CmdRemoveStruct
		err := wsfsprotocol.ReadCmdRemoveStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdRemove(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdRmDir:
		var req wsfsprotocol.CmdRmDirStruct
		err := wsfsprotocol.ReadCmdRmDirStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdRmDir(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdFsStat:
		var req wsfsprotocol.CmdFsStatStruct
		err := wsfsprotocol.ReadCmdFsStatStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdFsStat(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdReadAt:
		var req wsfsprotocol.CmdReadAtStruct
		err := wsfsprotocol.ReadCmdReadAtStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdReadAt(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdWriteAt:
		var req wsfsprotocol.CmdWriteAtStruct
		dataBuf := s.acquireFastBuffer()
		err := wsfsprotocol.ReadCmdWriteAtStructFromReaderWithBuffer(&req, r, dataBuf)
		if err != nil {
			s.releaseFastBuffer(dataBuf)
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			defer s.releaseFastBuffer(dataBuf)
			s.cmdWriteAt(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdCopyFileRange:
		var req wsfsprotocol.CmdCopyFileRangeStruct
		err := wsfsprotocol.ReadCmdCopyFileRangeStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdCopyFileRange(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdRename:
		var req wsfsprotocol.CmdRenameStruct
		err := wsfsprotocol.ReadCmdRenameStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdRename(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdSetAttrByFD:
		var req wsfsprotocol.CmdSetAttrByFDStruct
		err := wsfsprotocol.ReadCmdSetAttrByFDStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdSetAttrByFD(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdTreeDir:
		var req wsfsprotocol.CmdTreeDirStruct
		err := wsfsprotocol.ReadCmdTreeDirStructFromReader(&req, r)
		if err != nil {
			goto BadCmdFormat
		}
		s.cmdGroup.Go(func() error {
			s.cmdTreeDir(clientMark, req)
			return nil
		})
		return
	case wsfsprotocol.CmdWriteStreamOpen:
		var req wsfsprotocol.CmdWriteStreamOpenStruct
		dataBuf := s.acquireFastBuffer()
		err := wsfsprotocol.ReadCmdWriteStreamOpenStructFromReaderWithBuffer(&req, r, dataBuf)
		if err != nil {
			s.releaseFastBuffer(dataBuf)
			goto BadCmdFormat
		}
		s.cmdWriteStreamOpen(clientMark, req)
		s.releaseFastBuffer(dataBuf)
		return
	case wsfsprotocol.CmdWriteStreamData:
		var req wsfsprotocol.CmdWriteStreamDataStruct
		dataBuf := s.acquireFastBuffer()
		err := wsfsprotocol.ReadCmdWriteStreamDataStructFromReaderWithBuffer(&req, r, dataBuf)
		if err != nil {
			s.releaseFastBuffer(dataBuf)
			goto BadCmdFormat
		}
		s.cmdWriteStreamData(clientMark, req)
		s.releaseFastBuffer(dataBuf)
		return
	default:
		s.writeRspError(clientMark, wsfsprotocol.ErrorInvail, "Unknown command")
	}
	return
BadCmdFormat:
	s.writeRspError(clientMark, wsfsprotocol.ErrorInvail, "Bad command format")
	return
}
