//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"
)

const banner = "// Code generated by 'genCommandCalls.go'. DO NOT EDIT."

var syncCommands = map[string]bool{
	"CmdWriteStreamOpen": true,
	"CmdWriteStreamData": true,
}

type command struct {
	ConstName  string
	StructName string
	MethodName string
	HasBytes   bool
	Sync       bool
}

func parseBytesStructs(srcPath string) (map[string]bool, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, srcPath, nil, 0)
	if err != nil {
		return nil, err
	}

	bytesStructs := map[string]bool{}
	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, field := range structType.Fields.List {
				if types.ExprString(field.Type) == "[]byte" {
					bytesStructs[typeSpec.Name.Name] = true
					break
				}
			}
		}
	}

	return bytesStructs, nil
}

func parseCommands(srcPath string) ([]command, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, srcPath, nil, 0)
	if err != nil {
		return nil, err
	}

	commands := []command{}
	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}

		for _, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for _, name := range valueSpec.Names {
				if !strings.HasPrefix(name.Name, "Cmd") {
					continue
				}

				baseName := strings.TrimPrefix(name.Name, "Cmd")
				commands = append(commands, command{
					ConstName:  name.Name,
					StructName: name.Name + "Struct",
					MethodName: "cmd" + baseName,
					Sync:       syncCommands[name.Name],
				})
			}
		}
	}

	return commands, nil
}

func genCommandCalls(commands []command, packageName string) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "%s\n", banner)
	fmt.Fprintf(&buf, "package %s\n\n", packageName)
	fmt.Fprintf(&buf, "import (\n")
	fmt.Fprintf(&buf, "\"io\"\n")
	fmt.Fprintf(&buf, "\"wsfs-core/internal/share/wsfsprotocol\"\n")
	fmt.Fprintf(&buf, ")\n\n")

	fmt.Fprintf(&buf, "func (s *session) doCommandCall(clientMark, cmd uint8, r io.Reader) {\n")
	fmt.Fprintf(&buf, "switch cmd {\n")
	for _, cmd := range commands {
		fmt.Fprintf(&buf, "case wsfsprotocol.%s:\n", cmd.ConstName)
		fmt.Fprintf(&buf, "var req wsfsprotocol.%s\n", cmd.StructName)
		if cmd.HasBytes {
			fmt.Fprintf(&buf, "dataBuf := s.acquireFastBuffer()\n")
			fmt.Fprintf(&buf, "err := wsfsprotocol.Read%sFromReaderWithBuffer(&req, r, dataBuf)\n", cmd.StructName)
			fmt.Fprintf(&buf, "if err != nil {\n")
			fmt.Fprintf(&buf, "s.releaseFastBuffer(dataBuf)\n")
			fmt.Fprintf(&buf, "goto BadCmdFormat\n")
			fmt.Fprintf(&buf, "}\n")
			if cmd.Sync {
				fmt.Fprintf(&buf, "s.%s(clientMark, req)\n", cmd.MethodName)
				fmt.Fprintf(&buf, "s.releaseFastBuffer(dataBuf)\n")
			} else {
				fmt.Fprintf(&buf, "s.cmdGroup.Go(func() error {\n")
				fmt.Fprintf(&buf, "defer s.releaseFastBuffer(dataBuf)\n")
				fmt.Fprintf(&buf, "s.%s(clientMark, req)\n", cmd.MethodName)
				fmt.Fprintf(&buf, "return nil\n")
				fmt.Fprintf(&buf, "})\n")
			}
			fmt.Fprintf(&buf, "return\n")
		} else {
			fmt.Fprintf(&buf, "err := wsfsprotocol.Read%sFromReader(&req, r)\n", cmd.StructName)
			fmt.Fprintf(&buf, "if err != nil {\n")
			fmt.Fprintf(&buf, "goto BadCmdFormat\n")
			fmt.Fprintf(&buf, "}\n")
			if cmd.Sync {
				fmt.Fprintf(&buf, "s.%s(clientMark, req)\n", cmd.MethodName)
			} else {
				fmt.Fprintf(&buf, "s.cmdGroup.Go(func() error {\n")
				fmt.Fprintf(&buf, "s.%s(clientMark, req)\n", cmd.MethodName)
				fmt.Fprintf(&buf, "return nil\n")
				fmt.Fprintf(&buf, "})\n")
			}
			fmt.Fprintf(&buf, "return\n")
		}
	}
	fmt.Fprintf(&buf, "default:\n")
	fmt.Fprintf(&buf, "s.writeRspError(clientMark, wsfsprotocol.ErrorInvalid, \"Unknown command\")\n")
	fmt.Fprintf(&buf, "}\n")
	fmt.Fprintf(&buf, "return\n")
	fmt.Fprintf(&buf, "BadCmdFormat:\n")
	fmt.Fprintf(&buf, "s.writeRspError(clientMark, wsfsprotocol.ErrorInvalid, \"Bad command format\")\n")
	fmt.Fprintf(&buf, "return\n")
	fmt.Fprintf(&buf, "}\n")

	return format.Source(buf.Bytes())
}

func main() {
	if len(os.Args) > 1 && os.Args[1] == "--" {
		os.Args = append(os.Args[:1], os.Args[2:]...)
	}

	if len(os.Args) != 4 {
		fmt.Println("Bad usage")
		os.Exit(1)
	}

	commands, err := parseCommands(os.Args[1])
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	bytesStructs, err := parseBytesStructs(filepath.Join(filepath.Dir(os.Args[1]), "struct.go"))
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	for i := range commands {
		commands[i].HasBytes = bytesStructs[commands[i].StructName]
	}

	out, err := genCommandCalls(commands, os.Args[3])
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	if err := os.WriteFile(os.Args[2], out, 0644); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
