//go:build ignore

package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"go/types"
	"maps"
	"os"
	"slices"
	"strings"
)

const (
	banner = "// Code generated by 'genStructHelper.go'. DO NOT EDIT."
)

type fieldInfo struct {
	Name string
	Type string
}

type structInfo struct {
	// this is not true POD, we just use this to check type and detect loop
	PODSize int

	BufSize int
	Fields  []fieldInfo
}

func (info *structInfo) hasBytesField() bool {
	for _, field := range info.Fields {
		if field.Type == "[]byte" {
			return true
		}
	}
	return false
}

var (
	inputFile  = "struct.go"
	outputFile = "structHelper"
	buildTag   string

	packageName string
	unsafeMode  bool // aka amd64 mode

	structInfos       = map[string]*structInfo{}
	sortedStructNames = []string{}
)

func parseStructInfos(srcPath string) error {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, srcPath, nil, parser.ParseComments)
	if err != nil {
		return err
	}

	ast.PreorderStack(node, nil, func(n ast.Node, _ []ast.Node) bool {
		if err != nil {
			return false
		}

		typeSpec, ok := n.(*ast.TypeSpec)
		if !ok {
			if fileT, ok := n.(*ast.File); ok {
				packageName = fileT.Name.Name
			}
			return true
		}

		structType, ok := typeSpec.Type.(*ast.StructType)
		if !ok {
			return true
		}

		info := &structInfo{
			PODSize: -1,
			Fields:  []fieldInfo{},
		}
		for _, field := range structType.Fields.List {
			if len(field.Names) == 0 {
				err = fmt.Errorf("not supported no name field in '%s'", typeSpec.Name.Name)
				return false
			}
			for _, name := range field.Names {
				fieldName := name.Name
				fieldType := types.ExprString(field.Type)
				info.Fields = append(info.Fields, fieldInfo{Name: fieldName, Type: fieldType})
			}
		}
		structInfos[typeSpec.Name.Name] = info
		return false
	})
	sortedStructNames = slices.Sorted(maps.Keys(structInfos))

	return err
}

var builtinTypesSize = map[string]uint64{
	"uint8":  1,
	"uint16": 2,
	"uint32": 4,
	"uint64": 8,
	"int8":   1,
	"int16":  2,
	"int32":  4,
	"int64":  8,

	//ignored
	"string": 0,
	"[]byte": 0,
}

func analyzeStructInfoPODSize() (n int) {
	for _, info := range structInfos {
		if info.PODSize >= 0 {
			continue
		}

		size := 0
		for _, field := range info.Fields {
			if bs, ok := builtinTypesSize[field.Type]; ok {
				size += int(bs)
			} else if si, ok := structInfos[field.Type]; ok && si.PODSize >= 0 {
				size += si.PODSize
			} else {
				size = -1
				break
			}
		}
		if size != -1 {
			info.PODSize = size
			n += 1
		}
	}
	return
}

func analyzeStructInfoBufSize() {
	for _, info := range structInfos {
		history := 0
		size := 0
		for _, field := range info.Fields {
			if bs, ok := builtinTypesSize[field.Type]; bs != 0 && ok {
				size += int(bs)
			} else {
				history = max(size, history)
				size = 0
			}
		}
		info.BufSize = max(size, history)
	}
}

func genGetRequiredSize(buf *bytes.Buffer) error {
	for _, typeName := range sortedStructNames {
		info := structInfos[typeName]

		fmt.Fprintf(buf, "func Get%sRequiredSize(d %s) int {\n", typeName, typeName)
		sizes := []string{}
		constSize := 0

		for _, field := range info.Fields {
			if bs, ok := builtinTypesSize[field.Type]; ok {
				if bs != 0 {
					constSize += int(bs)
				} else {
					if field.Type == "string" {
						constSize += 1
					}
					sizes = append(sizes, "len(d."+field.Name+")")
				}
			} else {
				sizes = append(sizes, "Get"+field.Type+"RequiredSize(d."+field.Name+")")
			}
		}

		sizes = append(sizes, fmt.Sprintf("%d", constSize))
		fmt.Fprintf(buf, "return %s\n", strings.Join(sizes, "+"))
		buf.WriteString("}\n\n")
	}
	return nil
}

func genWrite2Writer(buf *bytes.Buffer) error {
	for _, typeName := range sortedStructNames {
		info := structInfos[typeName]

		fmt.Fprintf(buf, "func Write%sToWriter(d %s, w io.Writer) error {\n", typeName, typeName)
		if !unsafeMode && info.BufSize > 0 {
			fmt.Fprintf(buf, "var buf [%d]byte\n", info.BufSize)
		}

		var bufOffset uint64
		writeFlushBuf := func() {
			if unsafeMode || bufOffset == 0 || info.BufSize <= 0 {
				return
			}
			fmt.Fprintf(buf, "if _, err := w.Write(buf[:%d]); err != nil {\n", bufOffset)
			buf.WriteString("return err\n")
			buf.WriteString("}\n")
			bufOffset = 0
		}

		for _, field := range info.Fields {
			fmt.Fprintf(buf, "// %s %s\n", field.Name, field.Type)

			if bs, ok := builtinTypesSize[field.Type]; bs != 0 && ok {
				if unsafeMode {
					fmt.Fprintf(buf, "if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.%s)), %d)); err != nil {\n", field.Name, bs)
					buf.WriteString("return err\n")
					buf.WriteString("}\n")
				} else {
					if bs == 1 {
						fmt.Fprintf(buf, "buf[%d] = byte(d.%s)\n", bufOffset, field.Name)
					} else {
						fmt.Fprintf(buf, "binary.LittleEndian.PutUint%d(buf[%d:], uint%d(d.%s))\n", bs*8, bufOffset, bs*8, field.Name)
					}
					bufOffset += bs
				}
			} else if field.Type == "string" {
				writeFlushBuf()
				if unsafeMode {
					fmt.Fprintf(buf, "if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.%s), len(d.%s))); err != nil {\n", field.Name, field.Name)
				} else {
					fmt.Fprintf(buf, "if _, err := w.Write([]byte(d.%s)); err != nil {\n", field.Name)
				}
				buf.WriteString("return err\n")
				buf.WriteString("}\n")
				if unsafeMode {
					buf.WriteString("if _, err := w.Write([]byte{0}); err != nil {\n")
				} else {
					buf.WriteString("if _, err := w.Write([]byte{0}); err != nil {\n")
				}
				buf.WriteString("return err\n")
				buf.WriteString("}\n")
			} else if field.Type == "[]byte" {
				writeFlushBuf()
				if unsafeMode {
					fmt.Fprintf(buf, "if _, err := w.Write(d.%s); err != nil {\n", field.Name)
				} else {
					fmt.Fprintf(buf, "if _, err := w.Write(d.%s); err != nil {\n", field.Name)
				}
				buf.WriteString("return err\n")
				buf.WriteString("}\n")
			} else if _, ok := structInfos[field.Type]; ok {
				writeFlushBuf()
				fmt.Fprintf(buf, "if err := Write%sToWriter(d.%s, w); err != nil {\n", field.Type, field.Name)
				buf.WriteString("return err\n")
				buf.WriteString("}\n")
			} else {
				return fmt.Errorf("Unknown type: %s", field.Type)
			}

		}
		writeFlushBuf()
		buf.WriteString("return nil\n")
		buf.WriteString("}\n\n")
	}
	return nil
}

func genReadFromReader(buf *bytes.Buffer) error {
	for _, typeName := range sortedStructNames {
		info := structInfos[typeName]

		fmt.Fprintf(buf, "func Read%sFromReader(d *%s, r io.Reader) error {\n", typeName, typeName)
		if !unsafeMode && info.BufSize > 0 {
			fmt.Fprintf(buf, "var buf [%d]byte\n", info.BufSize)
		}

		var bufOffset uint64
		var bufStmts []string
		flushBuf := func() {
			if unsafeMode || bufOffset == 0 || info.BufSize <= 0 {
				return
			}
			fmt.Fprintf(buf, "if _, err := io.ReadFull(r, buf[:%d]); err != nil {\n", bufOffset)
			buf.WriteString("return err\n")
			buf.WriteString("}\n")
			for _, stmt := range bufStmts {
				buf.WriteString(stmt)
				buf.WriteRune('\n')
			}
			bufOffset = 0
			bufStmts = nil
		}

		for i, field := range info.Fields {
			fmt.Fprintf(buf, "// %s %s\n", field.Name, field.Type)

			if bs, ok := builtinTypesSize[field.Type]; bs != 0 && ok {
				if unsafeMode {
					fmt.Fprintf(buf, "if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.%s)), %d)); err != nil {\n", field.Name, bs)
					fmt.Fprintf(buf, "return err\n")
					fmt.Fprintf(buf, "}\n")
				} else {
					if bs == 1 {
						bufStmts = append(bufStmts, fmt.Sprintf("d.%s = (%s)(buf[%d])", field.Name, field.Type, bufOffset))
					} else {
						bufStmts = append(bufStmts, fmt.Sprintf("d.%s = (%s)(binary.LittleEndian.Uint%d(buf[%d:]))", field.Name, field.Type, bs*8, bufOffset))
					}
					bufOffset += bs
				}
			} else if field.Type == "string" {
				flushBuf()
				fmt.Fprintf(buf, "if err := CopyStrFromReader(r, &d.%s); err != nil {\n", field.Name)
				fmt.Fprintf(buf, "return err\n")
				fmt.Fprintf(buf, "}\n")
			} else if field.Type == "[]byte" {
				flushBuf()
				if i != len(info.Fields)-1 {
					return fmt.Errorf("[]byte not in the end of struct '%s'", typeName)
				}
				fmt.Fprintf(buf, "var err error\n")
				fmt.Fprintf(buf, "d.%s, err = io.ReadAll(r)\n", field.Name)
				fmt.Fprintf(buf, "if err != nil {\n")
				fmt.Fprintf(buf, "return err\n")
				fmt.Fprintf(buf, "}\n")
			} else {
				flushBuf()
				fmt.Fprintf(buf, "if err := Read%sFromReader(&d.%s, r); err != nil {\n", field.Type, field.Name)
				fmt.Fprintf(buf, "return err\n")
				fmt.Fprintf(buf, "}\n")
			}
		}
		flushBuf()
		buf.WriteString("return nil\n")
		buf.WriteString("}\n\n")
	}
	return nil
}

func genReadWithBufferFromReader(buf *bytes.Buffer) error {
	for _, typeName := range sortedStructNames {
		info := structInfos[typeName]
		if !info.hasBytesField() {
			continue
		}

		fmt.Fprintf(buf, "func Read%sFromReaderWithBuffer(d *%s, r io.Reader, dataBuf []byte) error {\n", typeName, typeName)
		if !unsafeMode && info.BufSize > 0 {
			fmt.Fprintf(buf, "var buf [%d]byte\n", info.BufSize)
		}

		var bufOffset uint64
		var bufStmts []string
		flushBuf := func() {
			if unsafeMode || bufOffset == 0 || info.BufSize <= 0 {
				return
			}
			fmt.Fprintf(buf, "if _, err := io.ReadFull(r, buf[:%d]); err != nil {\n", bufOffset)
			buf.WriteString("return err\n")
			buf.WriteString("}\n")
			for _, stmt := range bufStmts {
				buf.WriteString(stmt)
				buf.WriteRune('\n')
			}
			bufOffset = 0
			bufStmts = nil
		}

		for i, field := range info.Fields {
			fmt.Fprintf(buf, "// %s %s\n", field.Name, field.Type)

			if bs, ok := builtinTypesSize[field.Type]; bs != 0 && ok {
				if unsafeMode {
					fmt.Fprintf(buf, "if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.%s)), %d)); err != nil {\n", field.Name, bs)
					fmt.Fprintf(buf, "return err\n")
					fmt.Fprintf(buf, "}\n")
				} else {
					if bs == 1 {
						bufStmts = append(bufStmts, fmt.Sprintf("d.%s = (%s)(buf[%d])", field.Name, field.Type, bufOffset))
					} else {
						bufStmts = append(bufStmts, fmt.Sprintf("d.%s = (%s)(binary.LittleEndian.Uint%d(buf[%d:]))", field.Name, field.Type, bs*8, bufOffset))
					}
					bufOffset += bs
				}
			} else if field.Type == "string" {
				flushBuf()
				fmt.Fprintf(buf, "if err := CopyStrFromReader(r, &d.%s); err != nil {\n", field.Name)
				fmt.Fprintf(buf, "return err\n")
				fmt.Fprintf(buf, "}\n")
			} else if field.Type == "[]byte" {
				flushBuf()
				if i != len(info.Fields)-1 {
					return fmt.Errorf("[]byte not in the end of struct '%s'", typeName)
				}
				fmt.Fprintf(buf, "var err error\n")
				fmt.Fprintf(buf, "d.%s, err = readAllToBuffer(r, dataBuf)\n", field.Name)
				fmt.Fprintf(buf, "if err != nil {\n")
				fmt.Fprintf(buf, "return err\n")
				fmt.Fprintf(buf, "}\n")
			} else {
				flushBuf()
				fmt.Fprintf(buf, "if err := Read%sFromReader(&d.%s, r); err != nil {\n", field.Type, field.Name)
				fmt.Fprintf(buf, "return err\n")
				fmt.Fprintf(buf, "}\n")
			}
		}
		flushBuf()
		buf.WriteString("return nil\n")
		buf.WriteString("}\n\n")
	}
	return nil
}

func genBytesCommentAndHelper(buf *bytes.Buffer) {
	bytesStructs := []string{}
	for _, typeName := range sortedStructNames {
		if structInfos[typeName].hasBytesField() {
			bytesStructs = append(bytesStructs, typeName)
		}
	}

	buf.WriteString("/*\nCommand structs with []byte payload fields:\n")
	if len(bytesStructs) == 0 {
		buf.WriteString("  (none)\n")
	} else {
		for _, typeName := range bytesStructs {
			if !strings.HasPrefix(typeName, "Cmd") {
				continue
			}
			buf.WriteString("  - " + typeName + "\n")
		}
	}
	buf.WriteString("*/\n\n")

	if len(bytesStructs) == 0 {
		return
	}

	buf.WriteString(`func readAllToBuffer(r io.Reader, dataBuf []byte) ([]byte, error) {
	n := 0
	for n < len(dataBuf) {
		readN, err := r.Read(dataBuf[n:])
		n += readN
		if err == io.EOF {
			return dataBuf[:n], nil
		}
		if err != nil {
			return nil, err
		}
	}

	var extra [1]byte
	readN, err := r.Read(extra[:])
	if readN > 0 {
		return nil, io.ErrShortBuffer
	}
	if err == io.EOF {
		return dataBuf[:n], nil
	}
	return nil, err
}

`)
}

func genHelper() error {
	writeTo := outputFile

	data, err := os.ReadFile(writeTo)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err == nil {
		if !strings.Contains(string(data[:min(len(banner)+64, len(data))]), banner) {
			return fmt.Errorf("'%s' exists and not generated code", writeTo)
		}
	}

	var buf bytes.Buffer
	buf.WriteString("package " + packageName + "\n\n")

	if unsafeMode {
		buf.WriteString(`import "unsafe"`)
	} else {
		buf.WriteString(`import "encoding/binary"`)
	}
	buf.WriteString(`
		import (
			"io"
		)
	`)

	if unsafeMode {
		buf.WriteString(`
//Note: Unsafe mode assume that:
// 1. target is native little-endian
// 2. target have good profmance in unaligned memory access
// 3. Reader/Writer is buffered

`)
	}
	genBytesCommentAndHelper(&buf)

	err = genGetRequiredSize(&buf)
	if err != nil {
		return err
	}
	err = genWrite2Writer(&buf)
	if err != nil {
		return err
	}
	err = genReadFromReader(&buf)
	if err != nil {
		return err
	}
	err = genReadWithBufferFromReader(&buf)
	if err != nil {
		return err
	}

	formated, err := format.Source(buf.Bytes())
	if err != nil {
		os.WriteFile(writeTo+".debug", buf.Bytes(), 0644)
		return fmt.Errorf("format error: %v", err)
	}

	// bypass format to avoid some strange behavior from format.Source().
	buf.Reset()
	buf.WriteString(banner + "\n")
	if buildTag != "" {
		fmt.Fprintf(&buf, "//go:build %s\n", buildTag)
	}
	buf.WriteString("\n")
	buf.Write(formated)

	return os.WriteFile(writeTo, buf.Bytes(), 0644)
}

func main() {
	if len(os.Args) != 5 || (os.Args[1] != "0" && os.Args[1] != "1") {
		fmt.Println("Bad usage")
		fmt.Printf("Usage: %s UNSAFE_MODE(0/1) BUILD_TAG INPUT_FILE OUTPUT_FILE\n", os.Args[0])
		os.Exit(1)
	}
	inputFile = os.Args[3]
	outputFile = os.Args[4]
	buildTag = os.Args[2]
	if os.Args[1] == "1" {
		unsafeMode = true
	}

	err := parseStructInfos(inputFile)
	if err != nil {
		fmt.Println("Unable to parse file:", err)
		os.Exit(1)
	}

	for {
		if analyzeStructInfoPODSize() == 0 {
			break
		}
	}
	analyzeStructInfoBufSize()
	// for name, info := range structInfos {
	// 	fmt.Println(name, info.PODSize)
	// 	for k, v := range info.Fields {
	// 		fmt.Println("\t", k, v)
	// 	}
	// }
	for name, info := range structInfos {
		if info.PODSize < 0 {
			fmt.Printf("Unable to analyze the size of struct '%s'\n", name)
			os.Exit(1)
		}
	}

	err = genHelper()
	if err != nil {
		fmt.Printf("failed to generate: %v\n", err)
		os.Exit(1)
	}
}
