// Code generated by 'genStructHelper.go'. DO NOT EDIT.
//go:build amd64

package wsfsprotocol

import "unsafe"
import (
	"io"
)

//Note: Unsafe mode assume that:
// 1. target is native little-endian
// 2. target have good profmance in unaligned memory access
// 3. Reader/Writer is buffered

/*
Command structs with []byte payload fields:
  - CmdWriteAtStruct
  - CmdWriteStreamDataStruct
  - CmdWriteStreamOpenStruct
  - CmdWriteStruct
*/

func readAllToBuffer(r io.Reader, dataBuf []byte) ([]byte, error) {
	n := 0
	for n < len(dataBuf) {
		readN, err := r.Read(dataBuf[n:])
		n += readN
		if err == io.EOF {
			return dataBuf[:n], nil
		}
		if err != nil {
			return nil, err
		}
	}

	var extra [1]byte
	readN, err := r.Read(extra[:])
	if readN > 0 {
		return nil, io.ErrShortBuffer
	}
	if err == io.EOF {
		return dataBuf[:n], nil
	}
	return nil, err
}

func GetCmdAllocateStructRequiredSize(d CmdAllocateStruct) int {
	return 24
}

func GetCmdCloseStructRequiredSize(d CmdCloseStruct) int {
	return 4
}

func GetCmdCopyFileRangeStructRequiredSize(d CmdCopyFileRangeStruct) int {
	return 32
}

func GetCmdFsStatStructRequiredSize(d CmdFsStatStruct) int {
	return len(d.Path) + 1
}

func GetCmdGetAttrStructRequiredSize(d CmdGetAttrStruct) int {
	return len(d.Path) + 1
}

func GetCmdMkdirStructRequiredSize(d CmdMkdirStruct) int {
	return len(d.Path) + 5
}

func GetCmdOpenStructRequiredSize(d CmdOpenStruct) int {
	return len(d.Path) + 9
}

func GetCmdReadAtStructRequiredSize(d CmdReadAtStruct) int {
	return 20
}

func GetCmdReadDirPlusStructRequiredSize(d CmdReadDirPlusStruct) int {
	return len(d.Path) + 1
}

func GetCmdReadDirStructRequiredSize(d CmdReadDirStruct) int {
	return len(d.Path) + 1
}

func GetCmdReadLinkStructRequiredSize(d CmdReadLinkStruct) int {
	return len(d.Path) + 1
}

func GetCmdReadStructRequiredSize(d CmdReadStruct) int {
	return 12
}

func GetCmdRemoveStructRequiredSize(d CmdRemoveStruct) int {
	return len(d.Path) + 1
}

func GetCmdRenameStructRequiredSize(d CmdRenameStruct) int {
	return len(d.OldPath) + len(d.NewPath) + 6
}

func GetCmdRmDirStructRequiredSize(d CmdRmDirStruct) int {
	return len(d.Path) + 1
}

func GetCmdSeekStructRequiredSize(d CmdSeekStruct) int {
	return 16
}

func GetCmdSetAttrByFDStructRequiredSize(d CmdSetAttrByFDStruct) int {
	return GetFileInfoRequiredSize(d.FI) + 5
}

func GetCmdSetAttrStructRequiredSize(d CmdSetAttrStruct) int {
	return len(d.Path) + GetFileInfoRequiredSize(d.FI) + 2
}

func GetCmdSymLinkStructRequiredSize(d CmdSymLinkStruct) int {
	return len(d.TargetPath) + len(d.FilePath) + 2
}

func GetCmdSyncStructRequiredSize(d CmdSyncStruct) int {
	return 4
}

func GetCmdWriteAtStructRequiredSize(d CmdWriteAtStruct) int {
	return len(d.Data) + 12
}

func GetCmdWriteStreamDataStructRequiredSize(d CmdWriteStreamDataStruct) int {
	return len(d.Data) + 1
}

func GetCmdWriteStreamOpenStructRequiredSize(d CmdWriteStreamOpenStruct) int {
	return len(d.Data) + 12
}

func GetCmdWriteStructRequiredSize(d CmdWriteStruct) int {
	return len(d.Data) + 4
}

func GetDirentRequiredSize(d Dirent) int {
	return len(d.Name) + 22
}

func GetFileInfoRequiredSize(d FileInfo) int {
	return 21
}

func GetRspAllocateRequiredSize(d RspAllocate) int {
	return 0
}

func GetRspCloseRequiredSize(d RspClose) int {
	return 0
}

func GetRspCopyFileRangeRequiredSize(d RspCopyFileRange) int {
	return 8
}

func GetRspErrorRequiredSize(d RspError) int {
	return len(d.Desc) + 1
}

func GetRspFsStatRequiredSize(d RspFsStat) int {
	return 24
}

func GetRspGetAttrRequiredSize(d RspGetAttr) int {
	return GetFileInfoRequiredSize(d.FI) + 0
}

func GetRspMkdirRequiredSize(d RspMkdir) int {
	return 0
}

func GetRspOpenRequiredSize(d RspOpen) int {
	return 4
}

func GetRspReadRequiredSize(d RspRead) int {
	return len(d.Data) + 0
}

func GetRspReadAtRequiredSize(d RspReadAt) int {
	return len(d.Data) + 0
}

func GetRspReadDirRequiredSize(d RspReadDir) int {
	return len(d.Data) + 0
}

func GetRspReadLinkRequiredSize(d RspReadLink) int {
	return len(d.TargetPath) + 1
}

func GetRspRemoveRequiredSize(d RspRemove) int {
	return 0
}

func GetRspRenameRequiredSize(d RspRename) int {
	return 0
}

func GetRspRmDirRequiredSize(d RspRmDir) int {
	return 0
}

func GetRspSeekRequiredSize(d RspSeek) int {
	return 8
}

func GetRspSetAttrRequiredSize(d RspSetAttr) int {
	return 0
}

func GetRspSetAttrByFDRequiredSize(d RspSetAttrByFD) int {
	return 0
}

func GetRspSymLinkRequiredSize(d RspSymLink) int {
	return 0
}

func GetRspSyncRequiredSize(d RspSync) int {
	return 0
}

func GetRspWriteRequiredSize(d RspWrite) int {
	return 8
}

func GetRspWriteAtRequiredSize(d RspWriteAt) int {
	return 8
}

func GetRspWriteStreamCloseRequiredSize(d RspWriteStreamClose) int {
	return 8
}

func WriteCmdAllocateStructToWriter(d CmdAllocateStruct, w io.Writer) error {
	// FD uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Flag uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Flag)), 4)); err != nil {
		return err
	}
	// Offset uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Offset)), 8)); err != nil {
		return err
	}
	// Size uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Size)), 8)); err != nil {
		return err
	}
	return nil
}

func WriteCmdCloseStructToWriter(d CmdCloseStruct, w io.Writer) error {
	// FD uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	return nil
}

func WriteCmdCopyFileRangeStructToWriter(d CmdCopyFileRangeStruct, w io.Writer) error {
	// SrcFD uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.SrcFD)), 4)); err != nil {
		return err
	}
	// DstFD uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.DstFD)), 4)); err != nil {
		return err
	}
	// SrcOffset uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.SrcOffset)), 8)); err != nil {
		return err
	}
	// DstOffset uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.DstOffset)), 8)); err != nil {
		return err
	}
	// Size uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Size)), 8)); err != nil {
		return err
	}
	return nil
}

func WriteCmdFsStatStructToWriter(d CmdFsStatStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.Path), len(d.Path))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteCmdGetAttrStructToWriter(d CmdGetAttrStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.Path), len(d.Path))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteCmdMkdirStructToWriter(d CmdMkdirStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.Path), len(d.Path))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	// Mode uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Mode)), 4)); err != nil {
		return err
	}
	return nil
}

func WriteCmdOpenStructToWriter(d CmdOpenStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.Path), len(d.Path))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	// OFlag uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.OFlag)), 4)); err != nil {
		return err
	}
	// FMode uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.FMode)), 4)); err != nil {
		return err
	}
	return nil
}

func WriteCmdReadAtStructToWriter(d CmdReadAtStruct, w io.Writer) error {
	// FD uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Offset uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Offset)), 8)); err != nil {
		return err
	}
	// Size uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Size)), 8)); err != nil {
		return err
	}
	return nil
}

func WriteCmdReadDirPlusStructToWriter(d CmdReadDirPlusStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.Path), len(d.Path))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteCmdReadDirStructToWriter(d CmdReadDirStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.Path), len(d.Path))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteCmdReadLinkStructToWriter(d CmdReadLinkStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.Path), len(d.Path))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteCmdReadStructToWriter(d CmdReadStruct, w io.Writer) error {
	// FD uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Size uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Size)), 8)); err != nil {
		return err
	}
	return nil
}

func WriteCmdRemoveStructToWriter(d CmdRemoveStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.Path), len(d.Path))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteCmdRenameStructToWriter(d CmdRenameStruct, w io.Writer) error {
	// OldPath string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.OldPath), len(d.OldPath))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	// NewPath string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.NewPath), len(d.NewPath))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	// Flag uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Flag)), 4)); err != nil {
		return err
	}
	return nil
}

func WriteCmdRmDirStructToWriter(d CmdRmDirStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.Path), len(d.Path))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteCmdSeekStructToWriter(d CmdSeekStruct, w io.Writer) error {
	// FD uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Flag uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Flag)), 4)); err != nil {
		return err
	}
	// Offset int64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Offset)), 8)); err != nil {
		return err
	}
	return nil
}

func WriteCmdSetAttrByFDStructToWriter(d CmdSetAttrByFDStruct, w io.Writer) error {
	// FD uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Flag uint8
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Flag)), 1)); err != nil {
		return err
	}
	// FI FileInfo
	if err := WriteFileInfoToWriter(d.FI, w); err != nil {
		return err
	}
	return nil
}

func WriteCmdSetAttrStructToWriter(d CmdSetAttrStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.Path), len(d.Path))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	// Flag uint8
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Flag)), 1)); err != nil {
		return err
	}
	// FI FileInfo
	if err := WriteFileInfoToWriter(d.FI, w); err != nil {
		return err
	}
	return nil
}

func WriteCmdSymLinkStructToWriter(d CmdSymLinkStruct, w io.Writer) error {
	// TargetPath string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.TargetPath), len(d.TargetPath))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	// FilePath string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.FilePath), len(d.FilePath))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteCmdSyncStructToWriter(d CmdSyncStruct, w io.Writer) error {
	// FD uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	return nil
}

func WriteCmdWriteAtStructToWriter(d CmdWriteAtStruct, w io.Writer) error {
	// FD uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Offset uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Offset)), 8)); err != nil {
		return err
	}
	// Data []byte
	if _, err := w.Write(d.Data); err != nil {
		return err
	}
	return nil
}

func WriteCmdWriteStreamDataStructToWriter(d CmdWriteStreamDataStruct, w io.Writer) error {
	// IsEnd uint8
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.IsEnd)), 1)); err != nil {
		return err
	}
	// Data []byte
	if _, err := w.Write(d.Data); err != nil {
		return err
	}
	return nil
}

func WriteCmdWriteStreamOpenStructToWriter(d CmdWriteStreamOpenStruct, w io.Writer) error {
	// FD uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Offset uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Offset)), 8)); err != nil {
		return err
	}
	// Data []byte
	if _, err := w.Write(d.Data); err != nil {
		return err
	}
	return nil
}

func WriteCmdWriteStructToWriter(d CmdWriteStruct, w io.Writer) error {
	// FD uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Data []byte
	if _, err := w.Write(d.Data); err != nil {
		return err
	}
	return nil
}

func WriteDirentToWriter(d Dirent, w io.Writer) error {
	// Name string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.Name), len(d.Name))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	// Size uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Size)), 8)); err != nil {
		return err
	}
	// MTime int64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.MTime)), 8)); err != nil {
		return err
	}
	// Mode uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Mode)), 4)); err != nil {
		return err
	}
	// Owner uint8
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Owner)), 1)); err != nil {
		return err
	}
	return nil
}

func WriteFileInfoToWriter(d FileInfo, w io.Writer) error {
	// Size uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Size)), 8)); err != nil {
		return err
	}
	// MTime int64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.MTime)), 8)); err != nil {
		return err
	}
	// Mode uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Mode)), 4)); err != nil {
		return err
	}
	// Owner uint8
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Owner)), 1)); err != nil {
		return err
	}
	return nil
}

func WriteRspAllocateToWriter(d RspAllocate, w io.Writer) error {
	return nil
}

func WriteRspCloseToWriter(d RspClose, w io.Writer) error {
	return nil
}

func WriteRspCopyFileRangeToWriter(d RspCopyFileRange, w io.Writer) error {
	// Copied uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Copied)), 8)); err != nil {
		return err
	}
	return nil
}

func WriteRspErrorToWriter(d RspError, w io.Writer) error {
	// Desc string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.Desc), len(d.Desc))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteRspFsStatToWriter(d RspFsStat, w io.Writer) error {
	// Total uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Total)), 8)); err != nil {
		return err
	}
	// Free uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Free)), 8)); err != nil {
		return err
	}
	// Available uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Available)), 8)); err != nil {
		return err
	}
	return nil
}

func WriteRspGetAttrToWriter(d RspGetAttr, w io.Writer) error {
	// FI FileInfo
	if err := WriteFileInfoToWriter(d.FI, w); err != nil {
		return err
	}
	return nil
}

func WriteRspMkdirToWriter(d RspMkdir, w io.Writer) error {
	return nil
}

func WriteRspOpenToWriter(d RspOpen, w io.Writer) error {
	// FD uint32
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	return nil
}

func WriteRspReadToWriter(d RspRead, w io.Writer) error {
	// Data []byte
	if _, err := w.Write(d.Data); err != nil {
		return err
	}
	return nil
}

func WriteRspReadAtToWriter(d RspReadAt, w io.Writer) error {
	// Data []byte
	if _, err := w.Write(d.Data); err != nil {
		return err
	}
	return nil
}

func WriteRspReadDirToWriter(d RspReadDir, w io.Writer) error {
	// Data []byte
	if _, err := w.Write(d.Data); err != nil {
		return err
	}
	return nil
}

func WriteRspReadLinkToWriter(d RspReadLink, w io.Writer) error {
	// TargetPath string
	if _, err := w.Write(unsafe.Slice(unsafe.StringData(d.TargetPath), len(d.TargetPath))); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteRspRemoveToWriter(d RspRemove, w io.Writer) error {
	return nil
}

func WriteRspRenameToWriter(d RspRename, w io.Writer) error {
	return nil
}

func WriteRspRmDirToWriter(d RspRmDir, w io.Writer) error {
	return nil
}

func WriteRspSeekToWriter(d RspSeek, w io.Writer) error {
	// Offset uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Offset)), 8)); err != nil {
		return err
	}
	return nil
}

func WriteRspSetAttrToWriter(d RspSetAttr, w io.Writer) error {
	return nil
}

func WriteRspSetAttrByFDToWriter(d RspSetAttrByFD, w io.Writer) error {
	return nil
}

func WriteRspSymLinkToWriter(d RspSymLink, w io.Writer) error {
	return nil
}

func WriteRspSyncToWriter(d RspSync, w io.Writer) error {
	return nil
}

func WriteRspWriteToWriter(d RspWrite, w io.Writer) error {
	// Written uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Written)), 8)); err != nil {
		return err
	}
	return nil
}

func WriteRspWriteAtToWriter(d RspWriteAt, w io.Writer) error {
	// Written uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Written)), 8)); err != nil {
		return err
	}
	return nil
}

func WriteRspWriteStreamCloseToWriter(d RspWriteStreamClose, w io.Writer) error {
	// Written uint64
	if _, err := w.Write(unsafe.Slice((*byte)(unsafe.Pointer(&d.Written)), 8)); err != nil {
		return err
	}
	return nil
}

func ReadCmdAllocateStructFromReader(d *CmdAllocateStruct, r io.Reader) error {
	// FD uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Flag uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Flag)), 4)); err != nil {
		return err
	}
	// Offset uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Offset)), 8)); err != nil {
		return err
	}
	// Size uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Size)), 8)); err != nil {
		return err
	}
	return nil
}

func ReadCmdCloseStructFromReader(d *CmdCloseStruct, r io.Reader) error {
	// FD uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	return nil
}

func ReadCmdCopyFileRangeStructFromReader(d *CmdCopyFileRangeStruct, r io.Reader) error {
	// SrcFD uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.SrcFD)), 4)); err != nil {
		return err
	}
	// DstFD uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.DstFD)), 4)); err != nil {
		return err
	}
	// SrcOffset uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.SrcOffset)), 8)); err != nil {
		return err
	}
	// DstOffset uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.DstOffset)), 8)); err != nil {
		return err
	}
	// Size uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Size)), 8)); err != nil {
		return err
	}
	return nil
}

func ReadCmdFsStatStructFromReader(d *CmdFsStatStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	return nil
}

func ReadCmdGetAttrStructFromReader(d *CmdGetAttrStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	return nil
}

func ReadCmdMkdirStructFromReader(d *CmdMkdirStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	// Mode uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Mode)), 4)); err != nil {
		return err
	}
	return nil
}

func ReadCmdOpenStructFromReader(d *CmdOpenStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	// OFlag uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.OFlag)), 4)); err != nil {
		return err
	}
	// FMode uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.FMode)), 4)); err != nil {
		return err
	}
	return nil
}

func ReadCmdReadAtStructFromReader(d *CmdReadAtStruct, r io.Reader) error {
	// FD uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Offset uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Offset)), 8)); err != nil {
		return err
	}
	// Size uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Size)), 8)); err != nil {
		return err
	}
	return nil
}

func ReadCmdReadDirPlusStructFromReader(d *CmdReadDirPlusStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	return nil
}

func ReadCmdReadDirStructFromReader(d *CmdReadDirStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	return nil
}

func ReadCmdReadLinkStructFromReader(d *CmdReadLinkStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	return nil
}

func ReadCmdReadStructFromReader(d *CmdReadStruct, r io.Reader) error {
	// FD uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Size uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Size)), 8)); err != nil {
		return err
	}
	return nil
}

func ReadCmdRemoveStructFromReader(d *CmdRemoveStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	return nil
}

func ReadCmdRenameStructFromReader(d *CmdRenameStruct, r io.Reader) error {
	// OldPath string
	if err := CopyStrFromReader(r, &d.OldPath); err != nil {
		return err
	}
	// NewPath string
	if err := CopyStrFromReader(r, &d.NewPath); err != nil {
		return err
	}
	// Flag uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Flag)), 4)); err != nil {
		return err
	}
	return nil
}

func ReadCmdRmDirStructFromReader(d *CmdRmDirStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	return nil
}

func ReadCmdSeekStructFromReader(d *CmdSeekStruct, r io.Reader) error {
	// FD uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Flag uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Flag)), 4)); err != nil {
		return err
	}
	// Offset int64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Offset)), 8)); err != nil {
		return err
	}
	return nil
}

func ReadCmdSetAttrByFDStructFromReader(d *CmdSetAttrByFDStruct, r io.Reader) error {
	// FD uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Flag uint8
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Flag)), 1)); err != nil {
		return err
	}
	// FI FileInfo
	if err := ReadFileInfoFromReader(&d.FI, r); err != nil {
		return err
	}
	return nil
}

func ReadCmdSetAttrStructFromReader(d *CmdSetAttrStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	// Flag uint8
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Flag)), 1)); err != nil {
		return err
	}
	// FI FileInfo
	if err := ReadFileInfoFromReader(&d.FI, r); err != nil {
		return err
	}
	return nil
}

func ReadCmdSymLinkStructFromReader(d *CmdSymLinkStruct, r io.Reader) error {
	// TargetPath string
	if err := CopyStrFromReader(r, &d.TargetPath); err != nil {
		return err
	}
	// FilePath string
	if err := CopyStrFromReader(r, &d.FilePath); err != nil {
		return err
	}
	return nil
}

func ReadCmdSyncStructFromReader(d *CmdSyncStruct, r io.Reader) error {
	// FD uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	return nil
}

func ReadCmdWriteAtStructFromReader(d *CmdWriteAtStruct, r io.Reader) error {
	// FD uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Offset uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Offset)), 8)); err != nil {
		return err
	}
	// Data []byte
	var err error
	d.Data, err = io.ReadAll(r)
	if err != nil {
		return err
	}
	return nil
}

func ReadCmdWriteStreamDataStructFromReader(d *CmdWriteStreamDataStruct, r io.Reader) error {
	// IsEnd uint8
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.IsEnd)), 1)); err != nil {
		return err
	}
	// Data []byte
	var err error
	d.Data, err = io.ReadAll(r)
	if err != nil {
		return err
	}
	return nil
}

func ReadCmdWriteStreamOpenStructFromReader(d *CmdWriteStreamOpenStruct, r io.Reader) error {
	// FD uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Offset uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Offset)), 8)); err != nil {
		return err
	}
	// Data []byte
	var err error
	d.Data, err = io.ReadAll(r)
	if err != nil {
		return err
	}
	return nil
}

func ReadCmdWriteStructFromReader(d *CmdWriteStruct, r io.Reader) error {
	// FD uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Data []byte
	var err error
	d.Data, err = io.ReadAll(r)
	if err != nil {
		return err
	}
	return nil
}

func ReadDirentFromReader(d *Dirent, r io.Reader) error {
	// Name string
	if err := CopyStrFromReader(r, &d.Name); err != nil {
		return err
	}
	// Size uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Size)), 8)); err != nil {
		return err
	}
	// MTime int64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.MTime)), 8)); err != nil {
		return err
	}
	// Mode uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Mode)), 4)); err != nil {
		return err
	}
	// Owner uint8
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Owner)), 1)); err != nil {
		return err
	}
	return nil
}

func ReadFileInfoFromReader(d *FileInfo, r io.Reader) error {
	// Size uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Size)), 8)); err != nil {
		return err
	}
	// MTime int64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.MTime)), 8)); err != nil {
		return err
	}
	// Mode uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Mode)), 4)); err != nil {
		return err
	}
	// Owner uint8
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Owner)), 1)); err != nil {
		return err
	}
	return nil
}

func ReadRspAllocateFromReader(d *RspAllocate, r io.Reader) error {
	return nil
}

func ReadRspCloseFromReader(d *RspClose, r io.Reader) error {
	return nil
}

func ReadRspCopyFileRangeFromReader(d *RspCopyFileRange, r io.Reader) error {
	// Copied uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Copied)), 8)); err != nil {
		return err
	}
	return nil
}

func ReadRspErrorFromReader(d *RspError, r io.Reader) error {
	// Desc string
	if err := CopyStrFromReader(r, &d.Desc); err != nil {
		return err
	}
	return nil
}

func ReadRspFsStatFromReader(d *RspFsStat, r io.Reader) error {
	// Total uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Total)), 8)); err != nil {
		return err
	}
	// Free uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Free)), 8)); err != nil {
		return err
	}
	// Available uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Available)), 8)); err != nil {
		return err
	}
	return nil
}

func ReadRspGetAttrFromReader(d *RspGetAttr, r io.Reader) error {
	// FI FileInfo
	if err := ReadFileInfoFromReader(&d.FI, r); err != nil {
		return err
	}
	return nil
}

func ReadRspMkdirFromReader(d *RspMkdir, r io.Reader) error {
	return nil
}

func ReadRspOpenFromReader(d *RspOpen, r io.Reader) error {
	// FD uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	return nil
}

func ReadRspReadFromReader(d *RspRead, r io.Reader) error {
	// Data []byte
	var err error
	d.Data, err = io.ReadAll(r)
	if err != nil {
		return err
	}
	return nil
}

func ReadRspReadAtFromReader(d *RspReadAt, r io.Reader) error {
	// Data []byte
	var err error
	d.Data, err = io.ReadAll(r)
	if err != nil {
		return err
	}
	return nil
}

func ReadRspReadDirFromReader(d *RspReadDir, r io.Reader) error {
	// Data []byte
	var err error
	d.Data, err = io.ReadAll(r)
	if err != nil {
		return err
	}
	return nil
}

func ReadRspReadLinkFromReader(d *RspReadLink, r io.Reader) error {
	// TargetPath string
	if err := CopyStrFromReader(r, &d.TargetPath); err != nil {
		return err
	}
	return nil
}

func ReadRspRemoveFromReader(d *RspRemove, r io.Reader) error {
	return nil
}

func ReadRspRenameFromReader(d *RspRename, r io.Reader) error {
	return nil
}

func ReadRspRmDirFromReader(d *RspRmDir, r io.Reader) error {
	return nil
}

func ReadRspSeekFromReader(d *RspSeek, r io.Reader) error {
	// Offset uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Offset)), 8)); err != nil {
		return err
	}
	return nil
}

func ReadRspSetAttrFromReader(d *RspSetAttr, r io.Reader) error {
	return nil
}

func ReadRspSetAttrByFDFromReader(d *RspSetAttrByFD, r io.Reader) error {
	return nil
}

func ReadRspSymLinkFromReader(d *RspSymLink, r io.Reader) error {
	return nil
}

func ReadRspSyncFromReader(d *RspSync, r io.Reader) error {
	return nil
}

func ReadRspWriteFromReader(d *RspWrite, r io.Reader) error {
	// Written uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Written)), 8)); err != nil {
		return err
	}
	return nil
}

func ReadRspWriteAtFromReader(d *RspWriteAt, r io.Reader) error {
	// Written uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Written)), 8)); err != nil {
		return err
	}
	return nil
}

func ReadRspWriteStreamCloseFromReader(d *RspWriteStreamClose, r io.Reader) error {
	// Written uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Written)), 8)); err != nil {
		return err
	}
	return nil
}

func ReadCmdWriteAtStructFromReaderWithBuffer(d *CmdWriteAtStruct, r io.Reader, dataBuf []byte) error {
	// FD uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Offset uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Offset)), 8)); err != nil {
		return err
	}
	// Data []byte
	var err error
	d.Data, err = readAllToBuffer(r, dataBuf)
	if err != nil {
		return err
	}
	return nil
}

func ReadCmdWriteStreamDataStructFromReaderWithBuffer(d *CmdWriteStreamDataStruct, r io.Reader, dataBuf []byte) error {
	// IsEnd uint8
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.IsEnd)), 1)); err != nil {
		return err
	}
	// Data []byte
	var err error
	d.Data, err = readAllToBuffer(r, dataBuf)
	if err != nil {
		return err
	}
	return nil
}

func ReadCmdWriteStreamOpenStructFromReaderWithBuffer(d *CmdWriteStreamOpenStruct, r io.Reader, dataBuf []byte) error {
	// FD uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Offset uint64
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.Offset)), 8)); err != nil {
		return err
	}
	// Data []byte
	var err error
	d.Data, err = readAllToBuffer(r, dataBuf)
	if err != nil {
		return err
	}
	return nil
}

func ReadCmdWriteStructFromReaderWithBuffer(d *CmdWriteStruct, r io.Reader, dataBuf []byte) error {
	// FD uint32
	if _, err := io.ReadFull(r, unsafe.Slice((*byte)(unsafe.Pointer(&d.FD)), 4)); err != nil {
		return err
	}
	// Data []byte
	var err error
	d.Data, err = readAllToBuffer(r, dataBuf)
	if err != nil {
		return err
	}
	return nil
}

func ReadRspReadFromReaderWithBuffer(d *RspRead, r io.Reader, dataBuf []byte) error {
	// Data []byte
	var err error
	d.Data, err = readAllToBuffer(r, dataBuf)
	if err != nil {
		return err
	}
	return nil
}

func ReadRspReadAtFromReaderWithBuffer(d *RspReadAt, r io.Reader, dataBuf []byte) error {
	// Data []byte
	var err error
	d.Data, err = readAllToBuffer(r, dataBuf)
	if err != nil {
		return err
	}
	return nil
}

func ReadRspReadDirFromReaderWithBuffer(d *RspReadDir, r io.Reader, dataBuf []byte) error {
	// Data []byte
	var err error
	d.Data, err = readAllToBuffer(r, dataBuf)
	if err != nil {
		return err
	}
	return nil
}
