// Code generated by 'genStructHelper.go'. DO NOT EDIT.
//go:build !amd64

package wsfsprotocol

import "encoding/binary"
import (
	"io"
)

/*
Command structs with []byte payload fields:
  - CmdWriteAtStruct
  - CmdWriteStreamDataStruct
  - CmdWriteStreamOpenStruct
  - CmdWriteStruct
*/

func readAllToBuffer(r io.Reader, dataBuf []byte) ([]byte, error) {
	n := 0
	for n < len(dataBuf) {
		readN, err := r.Read(dataBuf[n:])
		n += readN
		if err == io.EOF {
			return dataBuf[:n], nil
		}
		if err != nil {
			return nil, err
		}
	}

	var extra [1]byte
	readN, err := r.Read(extra[:])
	if readN > 0 {
		return nil, io.ErrShortBuffer
	}
	if err == io.EOF {
		return dataBuf[:n], nil
	}
	return nil, err
}

func GetCmdAllocateStructRequiredSize(d CmdAllocateStruct) int {
	return 24
}

func GetCmdCloneFileRangeStructRequiredSize(d CmdCloneFileRangeStruct) int {
	return 32
}

func GetCmdCloseStructRequiredSize(d CmdCloseStruct) int {
	return 4
}

func GetCmdCopyFileRangeStructRequiredSize(d CmdCopyFileRangeStruct) int {
	return 32
}

func GetCmdFsStatStructRequiredSize(d CmdFsStatStruct) int {
	return len(d.Path) + 1
}

func GetCmdGetAttrStructRequiredSize(d CmdGetAttrStruct) int {
	return len(d.Path) + 1
}

func GetCmdGetFileLockStructRequiredSize(d CmdGetFileLockStruct) int {
	return GetFileLockInfoRequiredSize(d.FileLock) + 4
}

func GetCmdMkdirStructRequiredSize(d CmdMkdirStruct) int {
	return len(d.Path) + 5
}

func GetCmdOpenStructRequiredSize(d CmdOpenStruct) int {
	return len(d.Path) + 9
}

func GetCmdReadAtStructRequiredSize(d CmdReadAtStruct) int {
	return 20
}

func GetCmdReadDirPlusStructRequiredSize(d CmdReadDirPlusStruct) int {
	return len(d.Path) + 1
}

func GetCmdReadDirStructRequiredSize(d CmdReadDirStruct) int {
	return len(d.Path) + 1
}

func GetCmdReadLinkStructRequiredSize(d CmdReadLinkStruct) int {
	return len(d.Path) + 1
}

func GetCmdReadStructRequiredSize(d CmdReadStruct) int {
	return 12
}

func GetCmdRemoveStructRequiredSize(d CmdRemoveStruct) int {
	return len(d.Path) + 1
}

func GetCmdRenameStructRequiredSize(d CmdRenameStruct) int {
	return len(d.OldPath) + len(d.NewPath) + 6
}

func GetCmdRmDirStructRequiredSize(d CmdRmDirStruct) int {
	return len(d.Path) + 1
}

func GetCmdSeekStructRequiredSize(d CmdSeekStruct) int {
	return 13
}

func GetCmdSetAttrByFDStructRequiredSize(d CmdSetAttrByFDStruct) int {
	return GetFileInfoRequiredSize(d.FI) + 5
}

func GetCmdSetAttrStructRequiredSize(d CmdSetAttrStruct) int {
	return len(d.Path) + GetFileInfoRequiredSize(d.FI) + 2
}

func GetCmdSetFileLockStructRequiredSize(d CmdSetFileLockStruct) int {
	return GetFileLockInfoRequiredSize(d.FileLock) + 4
}

func GetCmdSetFileLockWaitStructRequiredSize(d CmdSetFileLockWaitStruct) int {
	return GetFileLockInfoRequiredSize(d.FileLock) + 4
}

func GetCmdSymLinkStructRequiredSize(d CmdSymLinkStruct) int {
	return len(d.TargetPath) + len(d.FilePath) + 2
}

func GetCmdSyncStructRequiredSize(d CmdSyncStruct) int {
	return 4
}

func GetCmdWriteAtStructRequiredSize(d CmdWriteAtStruct) int {
	return len(d.Data) + 12
}

func GetCmdWriteStreamDataStructRequiredSize(d CmdWriteStreamDataStruct) int {
	return len(d.Data) + 1
}

func GetCmdWriteStreamOpenStructRequiredSize(d CmdWriteStreamOpenStruct) int {
	return len(d.Data) + 12
}

func GetCmdWriteStructRequiredSize(d CmdWriteStruct) int {
	return len(d.Data) + 4
}

func GetDirentRequiredSize(d Dirent) int {
	return len(d.Name) + GetTimespecRequiredSize(d.MTime) + 14
}

func GetFileInfoRequiredSize(d FileInfo) int {
	return GetTimespecRequiredSize(d.MTime) + 13
}

func GetFileLockInfoRequiredSize(d FileLockInfo) int {
	return 18
}

func GetRspAllocateRequiredSize(d RspAllocate) int {
	return 0
}

func GetRspCloneFileRangeRequiredSize(d RspCloneFileRange) int {
	return 0
}

func GetRspCloseRequiredSize(d RspClose) int {
	return 0
}

func GetRspCopyFileRangeRequiredSize(d RspCopyFileRange) int {
	return 8
}

func GetRspErrorRequiredSize(d RspError) int {
	return len(d.Desc) + 1
}

func GetRspFsStatRequiredSize(d RspFsStat) int {
	return 24
}

func GetRspGetAttrRequiredSize(d RspGetAttr) int {
	return GetFileInfoRequiredSize(d.FI) + 0
}

func GetRspGetFileLockRequiredSize(d RspGetFileLock) int {
	return GetFileLockInfoRequiredSize(d.FileLock) + 0
}

func GetRspMkdirRequiredSize(d RspMkdir) int {
	return 0
}

func GetRspOpenRequiredSize(d RspOpen) int {
	return 4
}

func GetRspReadRequiredSize(d RspRead) int {
	return len(d.Data) + 0
}

func GetRspReadAtRequiredSize(d RspReadAt) int {
	return len(d.Data) + 0
}

func GetRspReadDirRequiredSize(d RspReadDir) int {
	return len(d.Data) + 0
}

func GetRspReadLinkRequiredSize(d RspReadLink) int {
	return len(d.TargetPath) + 1
}

func GetRspRemoveRequiredSize(d RspRemove) int {
	return 0
}

func GetRspRenameRequiredSize(d RspRename) int {
	return 0
}

func GetRspRmDirRequiredSize(d RspRmDir) int {
	return 0
}

func GetRspSeekRequiredSize(d RspSeek) int {
	return 8
}

func GetRspSetAttrRequiredSize(d RspSetAttr) int {
	return 0
}

func GetRspSetAttrByFDRequiredSize(d RspSetAttrByFD) int {
	return 0
}

func GetRspSetFileLockRequiredSize(d RspSetFileLock) int {
	return 0
}

func GetRspSetFileLockWaitRequiredSize(d RspSetFileLockWait) int {
	return 0
}

func GetRspSymLinkRequiredSize(d RspSymLink) int {
	return 0
}

func GetRspSyncRequiredSize(d RspSync) int {
	return 0
}

func GetRspWriteRequiredSize(d RspWrite) int {
	return 8
}

func GetRspWriteAtRequiredSize(d RspWriteAt) int {
	return 8
}

func GetRspWriteStreamCloseRequiredSize(d RspWriteStreamClose) int {
	return 8
}

func GetTimespecRequiredSize(d Timespec) int {
	return 16
}

func WriteCmdAllocateStructToWriter(d CmdAllocateStruct, w io.Writer) error {
	var buf [24]byte
	// FD uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.FD))
	// Flag uint32
	binary.LittleEndian.PutUint32(buf[4:], uint32(d.Flag))
	// Offset uint64
	binary.LittleEndian.PutUint64(buf[8:], uint64(d.Offset))
	// Size uint64
	binary.LittleEndian.PutUint64(buf[16:], uint64(d.Size))
	if _, err := w.Write(buf[:24]); err != nil {
		return err
	}
	return nil
}

func WriteCmdCloneFileRangeStructToWriter(d CmdCloneFileRangeStruct, w io.Writer) error {
	var buf [32]byte
	// SrcFD uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.SrcFD))
	// DstFD uint32
	binary.LittleEndian.PutUint32(buf[4:], uint32(d.DstFD))
	// SrcOffset uint64
	binary.LittleEndian.PutUint64(buf[8:], uint64(d.SrcOffset))
	// DstOffset uint64
	binary.LittleEndian.PutUint64(buf[16:], uint64(d.DstOffset))
	// Size uint64
	binary.LittleEndian.PutUint64(buf[24:], uint64(d.Size))
	if _, err := w.Write(buf[:32]); err != nil {
		return err
	}
	return nil
}

func WriteCmdCloseStructToWriter(d CmdCloseStruct, w io.Writer) error {
	var buf [4]byte
	// FD uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.FD))
	if _, err := w.Write(buf[:4]); err != nil {
		return err
	}
	return nil
}

func WriteCmdCopyFileRangeStructToWriter(d CmdCopyFileRangeStruct, w io.Writer) error {
	var buf [32]byte
	// SrcFD uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.SrcFD))
	// DstFD uint32
	binary.LittleEndian.PutUint32(buf[4:], uint32(d.DstFD))
	// SrcOffset uint64
	binary.LittleEndian.PutUint64(buf[8:], uint64(d.SrcOffset))
	// DstOffset uint64
	binary.LittleEndian.PutUint64(buf[16:], uint64(d.DstOffset))
	// Size uint64
	binary.LittleEndian.PutUint64(buf[24:], uint64(d.Size))
	if _, err := w.Write(buf[:32]); err != nil {
		return err
	}
	return nil
}

func WriteCmdFsStatStructToWriter(d CmdFsStatStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write([]byte(d.Path)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteCmdGetAttrStructToWriter(d CmdGetAttrStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write([]byte(d.Path)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteCmdGetFileLockStructToWriter(d CmdGetFileLockStruct, w io.Writer) error {
	var buf [4]byte
	// FD uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.FD))
	// FileLock FileLockInfo
	if _, err := w.Write(buf[:4]); err != nil {
		return err
	}
	if err := WriteFileLockInfoToWriter(d.FileLock, w); err != nil {
		return err
	}
	return nil
}

func WriteCmdMkdirStructToWriter(d CmdMkdirStruct, w io.Writer) error {
	var buf [4]byte
	// Path string
	if _, err := w.Write([]byte(d.Path)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	// Mode uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.Mode))
	if _, err := w.Write(buf[:4]); err != nil {
		return err
	}
	return nil
}

func WriteCmdOpenStructToWriter(d CmdOpenStruct, w io.Writer) error {
	var buf [8]byte
	// Path string
	if _, err := w.Write([]byte(d.Path)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	// OFlag uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.OFlag))
	// FMode uint32
	binary.LittleEndian.PutUint32(buf[4:], uint32(d.FMode))
	if _, err := w.Write(buf[:8]); err != nil {
		return err
	}
	return nil
}

func WriteCmdReadAtStructToWriter(d CmdReadAtStruct, w io.Writer) error {
	var buf [20]byte
	// FD uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.FD))
	// Offset uint64
	binary.LittleEndian.PutUint64(buf[4:], uint64(d.Offset))
	// Size uint64
	binary.LittleEndian.PutUint64(buf[12:], uint64(d.Size))
	if _, err := w.Write(buf[:20]); err != nil {
		return err
	}
	return nil
}

func WriteCmdReadDirPlusStructToWriter(d CmdReadDirPlusStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write([]byte(d.Path)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteCmdReadDirStructToWriter(d CmdReadDirStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write([]byte(d.Path)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteCmdReadLinkStructToWriter(d CmdReadLinkStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write([]byte(d.Path)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteCmdReadStructToWriter(d CmdReadStruct, w io.Writer) error {
	var buf [12]byte
	// FD uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.FD))
	// Size uint64
	binary.LittleEndian.PutUint64(buf[4:], uint64(d.Size))
	if _, err := w.Write(buf[:12]); err != nil {
		return err
	}
	return nil
}

func WriteCmdRemoveStructToWriter(d CmdRemoveStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write([]byte(d.Path)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteCmdRenameStructToWriter(d CmdRenameStruct, w io.Writer) error {
	var buf [4]byte
	// OldPath string
	if _, err := w.Write([]byte(d.OldPath)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	// NewPath string
	if _, err := w.Write([]byte(d.NewPath)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	// Flag uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.Flag))
	if _, err := w.Write(buf[:4]); err != nil {
		return err
	}
	return nil
}

func WriteCmdRmDirStructToWriter(d CmdRmDirStruct, w io.Writer) error {
	// Path string
	if _, err := w.Write([]byte(d.Path)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteCmdSeekStructToWriter(d CmdSeekStruct, w io.Writer) error {
	var buf [13]byte
	// FD uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.FD))
	// Whence uint8
	buf[4] = byte(d.Whence)
	// Offset int64
	binary.LittleEndian.PutUint64(buf[5:], uint64(d.Offset))
	if _, err := w.Write(buf[:13]); err != nil {
		return err
	}
	return nil
}

func WriteCmdSetAttrByFDStructToWriter(d CmdSetAttrByFDStruct, w io.Writer) error {
	var buf [5]byte
	// FD uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.FD))
	// Flag uint8
	buf[4] = byte(d.Flag)
	// FI FileInfo
	if _, err := w.Write(buf[:5]); err != nil {
		return err
	}
	if err := WriteFileInfoToWriter(d.FI, w); err != nil {
		return err
	}
	return nil
}

func WriteCmdSetAttrStructToWriter(d CmdSetAttrStruct, w io.Writer) error {
	var buf [1]byte
	// Path string
	if _, err := w.Write([]byte(d.Path)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	// Flag uint8
	buf[0] = byte(d.Flag)
	// FI FileInfo
	if _, err := w.Write(buf[:1]); err != nil {
		return err
	}
	if err := WriteFileInfoToWriter(d.FI, w); err != nil {
		return err
	}
	return nil
}

func WriteCmdSetFileLockStructToWriter(d CmdSetFileLockStruct, w io.Writer) error {
	var buf [4]byte
	// FD uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.FD))
	// FileLock FileLockInfo
	if _, err := w.Write(buf[:4]); err != nil {
		return err
	}
	if err := WriteFileLockInfoToWriter(d.FileLock, w); err != nil {
		return err
	}
	return nil
}

func WriteCmdSetFileLockWaitStructToWriter(d CmdSetFileLockWaitStruct, w io.Writer) error {
	var buf [4]byte
	// FD uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.FD))
	// FileLock FileLockInfo
	if _, err := w.Write(buf[:4]); err != nil {
		return err
	}
	if err := WriteFileLockInfoToWriter(d.FileLock, w); err != nil {
		return err
	}
	return nil
}

func WriteCmdSymLinkStructToWriter(d CmdSymLinkStruct, w io.Writer) error {
	// TargetPath string
	if _, err := w.Write([]byte(d.TargetPath)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	// FilePath string
	if _, err := w.Write([]byte(d.FilePath)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteCmdSyncStructToWriter(d CmdSyncStruct, w io.Writer) error {
	var buf [4]byte
	// FD uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.FD))
	if _, err := w.Write(buf[:4]); err != nil {
		return err
	}
	return nil
}

func WriteCmdWriteAtStructToWriter(d CmdWriteAtStruct, w io.Writer) error {
	var buf [12]byte
	// FD uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.FD))
	// Offset uint64
	binary.LittleEndian.PutUint64(buf[4:], uint64(d.Offset))
	// Data []byte
	if _, err := w.Write(buf[:12]); err != nil {
		return err
	}
	if _, err := w.Write(d.Data); err != nil {
		return err
	}
	return nil
}

func WriteCmdWriteStreamDataStructToWriter(d CmdWriteStreamDataStruct, w io.Writer) error {
	var buf [1]byte
	// IsEnd uint8
	buf[0] = byte(d.IsEnd)
	// Data []byte
	if _, err := w.Write(buf[:1]); err != nil {
		return err
	}
	if _, err := w.Write(d.Data); err != nil {
		return err
	}
	return nil
}

func WriteCmdWriteStreamOpenStructToWriter(d CmdWriteStreamOpenStruct, w io.Writer) error {
	var buf [12]byte
	// FD uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.FD))
	// Offset uint64
	binary.LittleEndian.PutUint64(buf[4:], uint64(d.Offset))
	// Data []byte
	if _, err := w.Write(buf[:12]); err != nil {
		return err
	}
	if _, err := w.Write(d.Data); err != nil {
		return err
	}
	return nil
}

func WriteCmdWriteStructToWriter(d CmdWriteStruct, w io.Writer) error {
	var buf [4]byte
	// FD uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.FD))
	// Data []byte
	if _, err := w.Write(buf[:4]); err != nil {
		return err
	}
	if _, err := w.Write(d.Data); err != nil {
		return err
	}
	return nil
}

func WriteDirentToWriter(d Dirent, w io.Writer) error {
	var buf [8]byte
	// Name string
	if _, err := w.Write([]byte(d.Name)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	// Size uint64
	binary.LittleEndian.PutUint64(buf[0:], uint64(d.Size))
	// MTime Timespec
	if _, err := w.Write(buf[:8]); err != nil {
		return err
	}
	if err := WriteTimespecToWriter(d.MTime, w); err != nil {
		return err
	}
	// Mode uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.Mode))
	// Owner uint8
	buf[4] = byte(d.Owner)
	if _, err := w.Write(buf[:5]); err != nil {
		return err
	}
	return nil
}

func WriteFileInfoToWriter(d FileInfo, w io.Writer) error {
	var buf [8]byte
	// Size uint64
	binary.LittleEndian.PutUint64(buf[0:], uint64(d.Size))
	// MTime Timespec
	if _, err := w.Write(buf[:8]); err != nil {
		return err
	}
	if err := WriteTimespecToWriter(d.MTime, w); err != nil {
		return err
	}
	// Mode uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.Mode))
	// Owner uint8
	buf[4] = byte(d.Owner)
	if _, err := w.Write(buf[:5]); err != nil {
		return err
	}
	return nil
}

func WriteFileLockInfoToWriter(d FileLockInfo, w io.Writer) error {
	var buf [18]byte
	// Type uint8
	buf[0] = byte(d.Type)
	// Whence uint8
	buf[1] = byte(d.Whence)
	// Start uint64
	binary.LittleEndian.PutUint64(buf[2:], uint64(d.Start))
	// Size uint64
	binary.LittleEndian.PutUint64(buf[10:], uint64(d.Size))
	if _, err := w.Write(buf[:18]); err != nil {
		return err
	}
	return nil
}

func WriteRspAllocateToWriter(d RspAllocate, w io.Writer) error {
	return nil
}

func WriteRspCloneFileRangeToWriter(d RspCloneFileRange, w io.Writer) error {
	return nil
}

func WriteRspCloseToWriter(d RspClose, w io.Writer) error {
	return nil
}

func WriteRspCopyFileRangeToWriter(d RspCopyFileRange, w io.Writer) error {
	var buf [8]byte
	// Copied uint64
	binary.LittleEndian.PutUint64(buf[0:], uint64(d.Copied))
	if _, err := w.Write(buf[:8]); err != nil {
		return err
	}
	return nil
}

func WriteRspErrorToWriter(d RspError, w io.Writer) error {
	// Desc string
	if _, err := w.Write([]byte(d.Desc)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteRspFsStatToWriter(d RspFsStat, w io.Writer) error {
	var buf [24]byte
	// Total uint64
	binary.LittleEndian.PutUint64(buf[0:], uint64(d.Total))
	// Free uint64
	binary.LittleEndian.PutUint64(buf[8:], uint64(d.Free))
	// Available uint64
	binary.LittleEndian.PutUint64(buf[16:], uint64(d.Available))
	if _, err := w.Write(buf[:24]); err != nil {
		return err
	}
	return nil
}

func WriteRspGetAttrToWriter(d RspGetAttr, w io.Writer) error {
	// FI FileInfo
	if err := WriteFileInfoToWriter(d.FI, w); err != nil {
		return err
	}
	return nil
}

func WriteRspGetFileLockToWriter(d RspGetFileLock, w io.Writer) error {
	// FileLock FileLockInfo
	if err := WriteFileLockInfoToWriter(d.FileLock, w); err != nil {
		return err
	}
	return nil
}

func WriteRspMkdirToWriter(d RspMkdir, w io.Writer) error {
	return nil
}

func WriteRspOpenToWriter(d RspOpen, w io.Writer) error {
	var buf [4]byte
	// FD uint32
	binary.LittleEndian.PutUint32(buf[0:], uint32(d.FD))
	if _, err := w.Write(buf[:4]); err != nil {
		return err
	}
	return nil
}

func WriteRspReadToWriter(d RspRead, w io.Writer) error {
	// Data []byte
	if _, err := w.Write(d.Data); err != nil {
		return err
	}
	return nil
}

func WriteRspReadAtToWriter(d RspReadAt, w io.Writer) error {
	// Data []byte
	if _, err := w.Write(d.Data); err != nil {
		return err
	}
	return nil
}

func WriteRspReadDirToWriter(d RspReadDir, w io.Writer) error {
	// Data []byte
	if _, err := w.Write(d.Data); err != nil {
		return err
	}
	return nil
}

func WriteRspReadLinkToWriter(d RspReadLink, w io.Writer) error {
	// TargetPath string
	if _, err := w.Write([]byte(d.TargetPath)); err != nil {
		return err
	}
	if _, err := w.Write([]byte{0}); err != nil {
		return err
	}
	return nil
}

func WriteRspRemoveToWriter(d RspRemove, w io.Writer) error {
	return nil
}

func WriteRspRenameToWriter(d RspRename, w io.Writer) error {
	return nil
}

func WriteRspRmDirToWriter(d RspRmDir, w io.Writer) error {
	return nil
}

func WriteRspSeekToWriter(d RspSeek, w io.Writer) error {
	var buf [8]byte
	// Offset uint64
	binary.LittleEndian.PutUint64(buf[0:], uint64(d.Offset))
	if _, err := w.Write(buf[:8]); err != nil {
		return err
	}
	return nil
}

func WriteRspSetAttrToWriter(d RspSetAttr, w io.Writer) error {
	return nil
}

func WriteRspSetAttrByFDToWriter(d RspSetAttrByFD, w io.Writer) error {
	return nil
}

func WriteRspSetFileLockToWriter(d RspSetFileLock, w io.Writer) error {
	return nil
}

func WriteRspSetFileLockWaitToWriter(d RspSetFileLockWait, w io.Writer) error {
	return nil
}

func WriteRspSymLinkToWriter(d RspSymLink, w io.Writer) error {
	return nil
}

func WriteRspSyncToWriter(d RspSync, w io.Writer) error {
	return nil
}

func WriteRspWriteToWriter(d RspWrite, w io.Writer) error {
	var buf [8]byte
	// Written uint64
	binary.LittleEndian.PutUint64(buf[0:], uint64(d.Written))
	if _, err := w.Write(buf[:8]); err != nil {
		return err
	}
	return nil
}

func WriteRspWriteAtToWriter(d RspWriteAt, w io.Writer) error {
	var buf [8]byte
	// Written uint64
	binary.LittleEndian.PutUint64(buf[0:], uint64(d.Written))
	if _, err := w.Write(buf[:8]); err != nil {
		return err
	}
	return nil
}

func WriteRspWriteStreamCloseToWriter(d RspWriteStreamClose, w io.Writer) error {
	var buf [8]byte
	// Written uint64
	binary.LittleEndian.PutUint64(buf[0:], uint64(d.Written))
	if _, err := w.Write(buf[:8]); err != nil {
		return err
	}
	return nil
}

func WriteTimespecToWriter(d Timespec, w io.Writer) error {
	var buf [16]byte
	// Seconds int64
	binary.LittleEndian.PutUint64(buf[0:], uint64(d.Seconds))
	// Nanoseconds int64
	binary.LittleEndian.PutUint64(buf[8:], uint64(d.Nanoseconds))
	if _, err := w.Write(buf[:16]); err != nil {
		return err
	}
	return nil
}

func ReadCmdAllocateStructFromReader(d *CmdAllocateStruct, r io.Reader) error {
	var buf [24]byte
	// FD uint32
	// Flag uint32
	// Offset uint64
	// Size uint64
	if _, err := io.ReadFull(r, buf[:24]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	d.Flag = (uint32)(binary.LittleEndian.Uint32(buf[4:]))
	d.Offset = (uint64)(binary.LittleEndian.Uint64(buf[8:]))
	d.Size = (uint64)(binary.LittleEndian.Uint64(buf[16:]))
	return nil
}

func ReadCmdCloneFileRangeStructFromReader(d *CmdCloneFileRangeStruct, r io.Reader) error {
	var buf [32]byte
	// SrcFD uint32
	// DstFD uint32
	// SrcOffset uint64
	// DstOffset uint64
	// Size uint64
	if _, err := io.ReadFull(r, buf[:32]); err != nil {
		return err
	}
	d.SrcFD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	d.DstFD = (uint32)(binary.LittleEndian.Uint32(buf[4:]))
	d.SrcOffset = (uint64)(binary.LittleEndian.Uint64(buf[8:]))
	d.DstOffset = (uint64)(binary.LittleEndian.Uint64(buf[16:]))
	d.Size = (uint64)(binary.LittleEndian.Uint64(buf[24:]))
	return nil
}

func ReadCmdCloseStructFromReader(d *CmdCloseStruct, r io.Reader) error {
	var buf [4]byte
	// FD uint32
	if _, err := io.ReadFull(r, buf[:4]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	return nil
}

func ReadCmdCopyFileRangeStructFromReader(d *CmdCopyFileRangeStruct, r io.Reader) error {
	var buf [32]byte
	// SrcFD uint32
	// DstFD uint32
	// SrcOffset uint64
	// DstOffset uint64
	// Size uint64
	if _, err := io.ReadFull(r, buf[:32]); err != nil {
		return err
	}
	d.SrcFD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	d.DstFD = (uint32)(binary.LittleEndian.Uint32(buf[4:]))
	d.SrcOffset = (uint64)(binary.LittleEndian.Uint64(buf[8:]))
	d.DstOffset = (uint64)(binary.LittleEndian.Uint64(buf[16:]))
	d.Size = (uint64)(binary.LittleEndian.Uint64(buf[24:]))
	return nil
}

func ReadCmdFsStatStructFromReader(d *CmdFsStatStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	return nil
}

func ReadCmdGetAttrStructFromReader(d *CmdGetAttrStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	return nil
}

func ReadCmdGetFileLockStructFromReader(d *CmdGetFileLockStruct, r io.Reader) error {
	var buf [4]byte
	// FD uint32
	// FileLock FileLockInfo
	if _, err := io.ReadFull(r, buf[:4]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	if err := ReadFileLockInfoFromReader(&d.FileLock, r); err != nil {
		return err
	}
	return nil
}

func ReadCmdMkdirStructFromReader(d *CmdMkdirStruct, r io.Reader) error {
	var buf [4]byte
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	// Mode uint32
	if _, err := io.ReadFull(r, buf[:4]); err != nil {
		return err
	}
	d.Mode = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	return nil
}

func ReadCmdOpenStructFromReader(d *CmdOpenStruct, r io.Reader) error {
	var buf [8]byte
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	// OFlag uint32
	// FMode uint32
	if _, err := io.ReadFull(r, buf[:8]); err != nil {
		return err
	}
	d.OFlag = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	d.FMode = (uint32)(binary.LittleEndian.Uint32(buf[4:]))
	return nil
}

func ReadCmdReadAtStructFromReader(d *CmdReadAtStruct, r io.Reader) error {
	var buf [20]byte
	// FD uint32
	// Offset uint64
	// Size uint64
	if _, err := io.ReadFull(r, buf[:20]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	d.Offset = (uint64)(binary.LittleEndian.Uint64(buf[4:]))
	d.Size = (uint64)(binary.LittleEndian.Uint64(buf[12:]))
	return nil
}

func ReadCmdReadDirPlusStructFromReader(d *CmdReadDirPlusStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	return nil
}

func ReadCmdReadDirStructFromReader(d *CmdReadDirStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	return nil
}

func ReadCmdReadLinkStructFromReader(d *CmdReadLinkStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	return nil
}

func ReadCmdReadStructFromReader(d *CmdReadStruct, r io.Reader) error {
	var buf [12]byte
	// FD uint32
	// Size uint64
	if _, err := io.ReadFull(r, buf[:12]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	d.Size = (uint64)(binary.LittleEndian.Uint64(buf[4:]))
	return nil
}

func ReadCmdRemoveStructFromReader(d *CmdRemoveStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	return nil
}

func ReadCmdRenameStructFromReader(d *CmdRenameStruct, r io.Reader) error {
	var buf [4]byte
	// OldPath string
	if err := CopyStrFromReader(r, &d.OldPath); err != nil {
		return err
	}
	// NewPath string
	if err := CopyStrFromReader(r, &d.NewPath); err != nil {
		return err
	}
	// Flag uint32
	if _, err := io.ReadFull(r, buf[:4]); err != nil {
		return err
	}
	d.Flag = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	return nil
}

func ReadCmdRmDirStructFromReader(d *CmdRmDirStruct, r io.Reader) error {
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	return nil
}

func ReadCmdSeekStructFromReader(d *CmdSeekStruct, r io.Reader) error {
	var buf [13]byte
	// FD uint32
	// Whence uint8
	// Offset int64
	if _, err := io.ReadFull(r, buf[:13]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	d.Whence = (uint8)(buf[4])
	d.Offset = (int64)(binary.LittleEndian.Uint64(buf[5:]))
	return nil
}

func ReadCmdSetAttrByFDStructFromReader(d *CmdSetAttrByFDStruct, r io.Reader) error {
	var buf [5]byte
	// FD uint32
	// Flag uint8
	// FI FileInfo
	if _, err := io.ReadFull(r, buf[:5]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	d.Flag = (uint8)(buf[4])
	if err := ReadFileInfoFromReader(&d.FI, r); err != nil {
		return err
	}
	return nil
}

func ReadCmdSetAttrStructFromReader(d *CmdSetAttrStruct, r io.Reader) error {
	var buf [1]byte
	// Path string
	if err := CopyStrFromReader(r, &d.Path); err != nil {
		return err
	}
	// Flag uint8
	// FI FileInfo
	if _, err := io.ReadFull(r, buf[:1]); err != nil {
		return err
	}
	d.Flag = (uint8)(buf[0])
	if err := ReadFileInfoFromReader(&d.FI, r); err != nil {
		return err
	}
	return nil
}

func ReadCmdSetFileLockStructFromReader(d *CmdSetFileLockStruct, r io.Reader) error {
	var buf [4]byte
	// FD uint32
	// FileLock FileLockInfo
	if _, err := io.ReadFull(r, buf[:4]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	if err := ReadFileLockInfoFromReader(&d.FileLock, r); err != nil {
		return err
	}
	return nil
}

func ReadCmdSetFileLockWaitStructFromReader(d *CmdSetFileLockWaitStruct, r io.Reader) error {
	var buf [4]byte
	// FD uint32
	// FileLock FileLockInfo
	if _, err := io.ReadFull(r, buf[:4]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	if err := ReadFileLockInfoFromReader(&d.FileLock, r); err != nil {
		return err
	}
	return nil
}

func ReadCmdSymLinkStructFromReader(d *CmdSymLinkStruct, r io.Reader) error {
	// TargetPath string
	if err := CopyStrFromReader(r, &d.TargetPath); err != nil {
		return err
	}
	// FilePath string
	if err := CopyStrFromReader(r, &d.FilePath); err != nil {
		return err
	}
	return nil
}

func ReadCmdSyncStructFromReader(d *CmdSyncStruct, r io.Reader) error {
	var buf [4]byte
	// FD uint32
	if _, err := io.ReadFull(r, buf[:4]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	return nil
}

func ReadCmdWriteAtStructFromReader(d *CmdWriteAtStruct, r io.Reader) error {
	var buf [12]byte
	// FD uint32
	// Offset uint64
	// Data []byte
	if _, err := io.ReadFull(r, buf[:12]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	d.Offset = (uint64)(binary.LittleEndian.Uint64(buf[4:]))
	var err error
	d.Data, err = io.ReadAll(r)
	if err != nil {
		return err
	}
	return nil
}

func ReadCmdWriteStreamDataStructFromReader(d *CmdWriteStreamDataStruct, r io.Reader) error {
	var buf [1]byte
	// IsEnd uint8
	// Data []byte
	if _, err := io.ReadFull(r, buf[:1]); err != nil {
		return err
	}
	d.IsEnd = (uint8)(buf[0])
	var err error
	d.Data, err = io.ReadAll(r)
	if err != nil {
		return err
	}
	return nil
}

func ReadCmdWriteStreamOpenStructFromReader(d *CmdWriteStreamOpenStruct, r io.Reader) error {
	var buf [12]byte
	// FD uint32
	// Offset uint64
	// Data []byte
	if _, err := io.ReadFull(r, buf[:12]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	d.Offset = (uint64)(binary.LittleEndian.Uint64(buf[4:]))
	var err error
	d.Data, err = io.ReadAll(r)
	if err != nil {
		return err
	}
	return nil
}

func ReadCmdWriteStructFromReader(d *CmdWriteStruct, r io.Reader) error {
	var buf [4]byte
	// FD uint32
	// Data []byte
	if _, err := io.ReadFull(r, buf[:4]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	var err error
	d.Data, err = io.ReadAll(r)
	if err != nil {
		return err
	}
	return nil
}

func ReadDirentFromReader(d *Dirent, r io.Reader) error {
	var buf [8]byte
	// Name string
	if err := CopyStrFromReader(r, &d.Name); err != nil {
		return err
	}
	// Size uint64
	// MTime Timespec
	if _, err := io.ReadFull(r, buf[:8]); err != nil {
		return err
	}
	d.Size = (uint64)(binary.LittleEndian.Uint64(buf[0:]))
	if err := ReadTimespecFromReader(&d.MTime, r); err != nil {
		return err
	}
	// Mode uint32
	// Owner uint8
	if _, err := io.ReadFull(r, buf[:5]); err != nil {
		return err
	}
	d.Mode = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	d.Owner = (uint8)(buf[4])
	return nil
}

func ReadFileInfoFromReader(d *FileInfo, r io.Reader) error {
	var buf [8]byte
	// Size uint64
	// MTime Timespec
	if _, err := io.ReadFull(r, buf[:8]); err != nil {
		return err
	}
	d.Size = (uint64)(binary.LittleEndian.Uint64(buf[0:]))
	if err := ReadTimespecFromReader(&d.MTime, r); err != nil {
		return err
	}
	// Mode uint32
	// Owner uint8
	if _, err := io.ReadFull(r, buf[:5]); err != nil {
		return err
	}
	d.Mode = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	d.Owner = (uint8)(buf[4])
	return nil
}

func ReadFileLockInfoFromReader(d *FileLockInfo, r io.Reader) error {
	var buf [18]byte
	// Type uint8
	// Whence uint8
	// Start uint64
	// Size uint64
	if _, err := io.ReadFull(r, buf[:18]); err != nil {
		return err
	}
	d.Type = (uint8)(buf[0])
	d.Whence = (uint8)(buf[1])
	d.Start = (uint64)(binary.LittleEndian.Uint64(buf[2:]))
	d.Size = (uint64)(binary.LittleEndian.Uint64(buf[10:]))
	return nil
}

func ReadRspAllocateFromReader(d *RspAllocate, r io.Reader) error {
	return nil
}

func ReadRspCloneFileRangeFromReader(d *RspCloneFileRange, r io.Reader) error {
	return nil
}

func ReadRspCloseFromReader(d *RspClose, r io.Reader) error {
	return nil
}

func ReadRspCopyFileRangeFromReader(d *RspCopyFileRange, r io.Reader) error {
	var buf [8]byte
	// Copied uint64
	if _, err := io.ReadFull(r, buf[:8]); err != nil {
		return err
	}
	d.Copied = (uint64)(binary.LittleEndian.Uint64(buf[0:]))
	return nil
}

func ReadRspErrorFromReader(d *RspError, r io.Reader) error {
	// Desc string
	if err := CopyStrFromReader(r, &d.Desc); err != nil {
		return err
	}
	return nil
}

func ReadRspFsStatFromReader(d *RspFsStat, r io.Reader) error {
	var buf [24]byte
	// Total uint64
	// Free uint64
	// Available uint64
	if _, err := io.ReadFull(r, buf[:24]); err != nil {
		return err
	}
	d.Total = (uint64)(binary.LittleEndian.Uint64(buf[0:]))
	d.Free = (uint64)(binary.LittleEndian.Uint64(buf[8:]))
	d.Available = (uint64)(binary.LittleEndian.Uint64(buf[16:]))
	return nil
}

func ReadRspGetAttrFromReader(d *RspGetAttr, r io.Reader) error {
	// FI FileInfo
	if err := ReadFileInfoFromReader(&d.FI, r); err != nil {
		return err
	}
	return nil
}

func ReadRspGetFileLockFromReader(d *RspGetFileLock, r io.Reader) error {
	// FileLock FileLockInfo
	if err := ReadFileLockInfoFromReader(&d.FileLock, r); err != nil {
		return err
	}
	return nil
}

func ReadRspMkdirFromReader(d *RspMkdir, r io.Reader) error {
	return nil
}

func ReadRspOpenFromReader(d *RspOpen, r io.Reader) error {
	var buf [4]byte
	// FD uint32
	if _, err := io.ReadFull(r, buf[:4]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	return nil
}

func ReadRspReadFromReader(d *RspRead, r io.Reader) error {
	// Data []byte
	var err error
	d.Data, err = io.ReadAll(r)
	if err != nil {
		return err
	}
	return nil
}

func ReadRspReadAtFromReader(d *RspReadAt, r io.Reader) error {
	// Data []byte
	var err error
	d.Data, err = io.ReadAll(r)
	if err != nil {
		return err
	}
	return nil
}

func ReadRspReadDirFromReader(d *RspReadDir, r io.Reader) error {
	// Data []byte
	var err error
	d.Data, err = io.ReadAll(r)
	if err != nil {
		return err
	}
	return nil
}

func ReadRspReadLinkFromReader(d *RspReadLink, r io.Reader) error {
	// TargetPath string
	if err := CopyStrFromReader(r, &d.TargetPath); err != nil {
		return err
	}
	return nil
}

func ReadRspRemoveFromReader(d *RspRemove, r io.Reader) error {
	return nil
}

func ReadRspRenameFromReader(d *RspRename, r io.Reader) error {
	return nil
}

func ReadRspRmDirFromReader(d *RspRmDir, r io.Reader) error {
	return nil
}

func ReadRspSeekFromReader(d *RspSeek, r io.Reader) error {
	var buf [8]byte
	// Offset uint64
	if _, err := io.ReadFull(r, buf[:8]); err != nil {
		return err
	}
	d.Offset = (uint64)(binary.LittleEndian.Uint64(buf[0:]))
	return nil
}

func ReadRspSetAttrFromReader(d *RspSetAttr, r io.Reader) error {
	return nil
}

func ReadRspSetAttrByFDFromReader(d *RspSetAttrByFD, r io.Reader) error {
	return nil
}

func ReadRspSetFileLockFromReader(d *RspSetFileLock, r io.Reader) error {
	return nil
}

func ReadRspSetFileLockWaitFromReader(d *RspSetFileLockWait, r io.Reader) error {
	return nil
}

func ReadRspSymLinkFromReader(d *RspSymLink, r io.Reader) error {
	return nil
}

func ReadRspSyncFromReader(d *RspSync, r io.Reader) error {
	return nil
}

func ReadRspWriteFromReader(d *RspWrite, r io.Reader) error {
	var buf [8]byte
	// Written uint64
	if _, err := io.ReadFull(r, buf[:8]); err != nil {
		return err
	}
	d.Written = (uint64)(binary.LittleEndian.Uint64(buf[0:]))
	return nil
}

func ReadRspWriteAtFromReader(d *RspWriteAt, r io.Reader) error {
	var buf [8]byte
	// Written uint64
	if _, err := io.ReadFull(r, buf[:8]); err != nil {
		return err
	}
	d.Written = (uint64)(binary.LittleEndian.Uint64(buf[0:]))
	return nil
}

func ReadRspWriteStreamCloseFromReader(d *RspWriteStreamClose, r io.Reader) error {
	var buf [8]byte
	// Written uint64
	if _, err := io.ReadFull(r, buf[:8]); err != nil {
		return err
	}
	d.Written = (uint64)(binary.LittleEndian.Uint64(buf[0:]))
	return nil
}

func ReadTimespecFromReader(d *Timespec, r io.Reader) error {
	var buf [16]byte
	// Seconds int64
	// Nanoseconds int64
	if _, err := io.ReadFull(r, buf[:16]); err != nil {
		return err
	}
	d.Seconds = (int64)(binary.LittleEndian.Uint64(buf[0:]))
	d.Nanoseconds = (int64)(binary.LittleEndian.Uint64(buf[8:]))
	return nil
}

func ReadCmdWriteAtStructFromReaderWithBuffer(d *CmdWriteAtStruct, r io.Reader, dataBuf []byte) error {
	var buf [12]byte
	// FD uint32
	// Offset uint64
	// Data []byte
	if _, err := io.ReadFull(r, buf[:12]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	d.Offset = (uint64)(binary.LittleEndian.Uint64(buf[4:]))
	var err error
	d.Data, err = readAllToBuffer(r, dataBuf)
	if err != nil {
		return err
	}
	return nil
}

func ReadCmdWriteStreamDataStructFromReaderWithBuffer(d *CmdWriteStreamDataStruct, r io.Reader, dataBuf []byte) error {
	var buf [1]byte
	// IsEnd uint8
	// Data []byte
	if _, err := io.ReadFull(r, buf[:1]); err != nil {
		return err
	}
	d.IsEnd = (uint8)(buf[0])
	var err error
	d.Data, err = readAllToBuffer(r, dataBuf)
	if err != nil {
		return err
	}
	return nil
}

func ReadCmdWriteStreamOpenStructFromReaderWithBuffer(d *CmdWriteStreamOpenStruct, r io.Reader, dataBuf []byte) error {
	var buf [12]byte
	// FD uint32
	// Offset uint64
	// Data []byte
	if _, err := io.ReadFull(r, buf[:12]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	d.Offset = (uint64)(binary.LittleEndian.Uint64(buf[4:]))
	var err error
	d.Data, err = readAllToBuffer(r, dataBuf)
	if err != nil {
		return err
	}
	return nil
}

func ReadCmdWriteStructFromReaderWithBuffer(d *CmdWriteStruct, r io.Reader, dataBuf []byte) error {
	var buf [4]byte
	// FD uint32
	// Data []byte
	if _, err := io.ReadFull(r, buf[:4]); err != nil {
		return err
	}
	d.FD = (uint32)(binary.LittleEndian.Uint32(buf[0:]))
	var err error
	d.Data, err = readAllToBuffer(r, dataBuf)
	if err != nil {
		return err
	}
	return nil
}

func ReadRspReadFromReaderWithBuffer(d *RspRead, r io.Reader, dataBuf []byte) error {
	// Data []byte
	var err error
	d.Data, err = readAllToBuffer(r, dataBuf)
	if err != nil {
		return err
	}
	return nil
}

func ReadRspReadAtFromReaderWithBuffer(d *RspReadAt, r io.Reader, dataBuf []byte) error {
	// Data []byte
	var err error
	d.Data, err = readAllToBuffer(r, dataBuf)
	if err != nil {
		return err
	}
	return nil
}

func ReadRspReadDirFromReaderWithBuffer(d *RspReadDir, r io.Reader, dataBuf []byte) error {
	// Data []byte
	var err error
	d.Data, err = readAllToBuffer(r, dataBuf)
	if err != nil {
		return err
	}
	return nil
}
