// Code generated by qtc from "error.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/server/webui/templates/error.qtpl:1
package templates

//line internal/server/webui/templates/error.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/server/webui/templates/error.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/server/webui/templates/error.qtpl:1
func StreamError(qw422016 *qt422016.Writer, cacheId string, status int, msg string, customCSS bool, customJS bool) {
//line internal/server/webui/templates/error.qtpl:1
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>`)
//line internal/server/webui/templates/error.qtpl:6
	qw422016.N().D(status)
//line internal/server/webui/templates/error.qtpl:6
	qw422016.N().S(` - WSFS WebUI</title>
    `)
//line internal/server/webui/templates/error.qtpl:7
	if customJS {
//line internal/server/webui/templates/error.qtpl:7
		qw422016.N().S(`<script src="/custom/custom.js?webui-assets=`)
//line internal/server/webui/templates/error.qtpl:7
		qw422016.N().S(cacheId)
//line internal/server/webui/templates/error.qtpl:7
		qw422016.N().S(`"></script>`)
//line internal/server/webui/templates/error.qtpl:7
	}
//line internal/server/webui/templates/error.qtpl:7
	qw422016.N().S(`
    <link rel="shortcut icon" href="/img/favicon.ico?webui-assets=`)
//line internal/server/webui/templates/error.qtpl:8
	qw422016.N().S(cacheId)
//line internal/server/webui/templates/error.qtpl:8
	qw422016.N().S(`">
    <link rel="stylesheet" type="text/css" href="/css/main.css?webui-assets=`)
//line internal/server/webui/templates/error.qtpl:9
	qw422016.N().S(cacheId)
//line internal/server/webui/templates/error.qtpl:9
	qw422016.N().S(`">
    `)
//line internal/server/webui/templates/error.qtpl:10
	if customCSS {
//line internal/server/webui/templates/error.qtpl:10
		qw422016.N().S(`<link rel="stylesheet" type="text/css" href="/custom/custom.css?webui-assets=`)
//line internal/server/webui/templates/error.qtpl:10
		qw422016.N().S(cacheId)
//line internal/server/webui/templates/error.qtpl:10
		qw422016.N().S(`">`)
//line internal/server/webui/templates/error.qtpl:10
	}
//line internal/server/webui/templates/error.qtpl:10
	qw422016.N().S(`
</head>
<body>
<main class="dialog column">
	<h1>`)
//line internal/server/webui/templates/error.qtpl:14
	qw422016.N().D(status)
//line internal/server/webui/templates/error.qtpl:14
	qw422016.N().S(`</h1>
    <p data-t>`)
//line internal/server/webui/templates/error.qtpl:15
	qw422016.E().S(msg)
//line internal/server/webui/templates/error.qtpl:15
	qw422016.N().S(`</p>
	<a style="text-align: right" href="/" data-t>Return to root</a>
</main>
</body>
<script src="/js/i18n.js?webui-assets=`)
//line internal/server/webui/templates/error.qtpl:19
	qw422016.N().S(cacheId)
//line internal/server/webui/templates/error.qtpl:19
	qw422016.N().S(`"></script>
</html>`)
//line internal/server/webui/templates/error.qtpl:20
}

//line internal/server/webui/templates/error.qtpl:20
func WriteError(qq422016 qtio422016.Writer, cacheId string, status int, msg string, customCSS bool, customJS bool) {
//line internal/server/webui/templates/error.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/server/webui/templates/error.qtpl:20
	StreamError(qw422016, cacheId, status, msg, customCSS, customJS)
//line internal/server/webui/templates/error.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line internal/server/webui/templates/error.qtpl:20
}

//line internal/server/webui/templates/error.qtpl:20
func Error(cacheId string, status int, msg string, customCSS bool, customJS bool) string {
//line internal/server/webui/templates/error.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/server/webui/templates/error.qtpl:20
	WriteError(qb422016, cacheId, status, msg, customCSS, customJS)
//line internal/server/webui/templates/error.qtpl:20
	qs422016 := string(qb422016.B)
//line internal/server/webui/templates/error.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/server/webui/templates/error.qtpl:20
	return qs422016
//line internal/server/webui/templates/error.qtpl:20
}
