// Code generated by qtc from "list.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line list.qtpl:1
package templates

//line list.qtpl:1
import (
	"github.com/dustin/go-humanize"
	"net/url"
	"strings"
	"time"
)

//line list.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line list.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line list.qtpl:9
type FileInfo struct {
	Name  string
	IsDir bool
	Size  int64
	MTime time.Time
}

//line list.qtpl:17
func StreamList(qw422016 *qt422016.Writer, cacheId string, paths []string, files []FileInfo, showDirSize bool) {
//line list.qtpl:17
	qw422016.N().S(`<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>`)
//line list.qtpl:23
	if len(paths) != 1 {
//line list.qtpl:23
		qw422016.E().S(paths[len(paths)-1])
//line list.qtpl:23
		qw422016.N().S(` - `)
//line list.qtpl:23
	}
//line list.qtpl:23
	qw422016.N().S(`WSFS WebUI</title>
    <link rel="shortcut icon" href="/img/favicon.ico?webui-assets=`)
//line list.qtpl:24
	qw422016.N().S(cacheId)
//line list.qtpl:24
	qw422016.N().S(`">
    <script src="/js/list.js?webui-assets=`)
//line list.qtpl:25
	qw422016.N().S(cacheId)
//line list.qtpl:25
	qw422016.N().S(`"></script>
    <link rel="stylesheet" type="text/css" href="/css/main.css?webui-assets=`)
//line list.qtpl:26
	qw422016.N().S(cacheId)
//line list.qtpl:26
	qw422016.N().S(`">
    <link rel="stylesheet" type="text/css" href="/css/list.css?webui-assets=`)
//line list.qtpl:27
	qw422016.N().S(cacheId)
//line list.qtpl:27
	qw422016.N().S(`">
</head>

<body>
    <main class="page column">
        <div class="path">`)
//line list.qtpl:33
	for i, path := range paths {
//line list.qtpl:33
		qw422016.N().S(`<a href="`)
//line list.qtpl:34
		qw422016.N().S(strings.Repeat("../", len(paths)-i-1))
//line list.qtpl:34
		qw422016.N().S(`">`)
//line list.qtpl:34
		qw422016.E().S(path)
//line list.qtpl:34
		qw422016.N().S(`</a>`)
//line list.qtpl:35
	}
//line list.qtpl:36
	qw422016.N().S(`
        </div>
        <div class="row">
		    <button type="button" onclick="OpenFileInputer()">
			    <span class="icon uploadFileIcon"></span><div data-t>Upload</div>
		    </button>
		    <button type="button" onclick="NewFolder()">
			    <span class="icon newFolderIcon"></span><div data-t>New folder</div>
		    </button>
	    </div>
        <table id="files">
            <thead>
            <th id="nameHeader" data-t>Name</th>
            <th id="sizeHeader" data-t>Size</th>
            <th id="timeHeader" data-t>Modification Time</th>`)
//line list.qtpl:50
	qw422016.N().S(`</thead><tbody>`)
//line list.qtpl:53
	for _, file := range files {
//line list.qtpl:54
		qw422016.N().S(`
`)
//line list.qtpl:54
		qw422016.N().S(`            `)
//line list.qtpl:54
		qw422016.N().S(`<tr`)
//line list.qtpl:55
		if file.IsDir {
//line list.qtpl:55
			qw422016.N().S(` `)
//line list.qtpl:55
			qw422016.N().S(`class="dirItem"`)
//line list.qtpl:55
		}
//line list.qtpl:55
		qw422016.N().S(`><td><div><a href="`)
//line list.qtpl:56
		qw422016.N().S((&url.URL{Path: file.Name}).EscapedPath())
//line list.qtpl:56
		if file.IsDir {
//line list.qtpl:56
			qw422016.N().S(`/`)
//line list.qtpl:56
		}
//line list.qtpl:56
		qw422016.N().S(`">`)
//line list.qtpl:56
		qw422016.E().S(file.Name)
//line list.qtpl:56
		qw422016.N().S(`</a></div></td>`)
//line list.qtpl:61
		qw422016.N().S(`<td>`)
//line list.qtpl:62
		if !file.IsDir || showDirSize {
//line list.qtpl:62
			qw422016.N().S(humanize.IBytes(uint64(file.Size)))
//line list.qtpl:62
		}
//line list.qtpl:62
		qw422016.N().S(`</td><td>`)
//line list.qtpl:63
		qw422016.N().S(file.MTime.Format("2006-01-02 15:04:05"))
//line list.qtpl:63
		qw422016.N().S(`</td></tr>`)
//line list.qtpl:65
	}
//line list.qtpl:66
	qw422016.N().S(`
            </tbody>
        </table>
    </main>
    <input type='file' id='FileInputer' style='opacity:0' onchange='UploadFiles()' multiple />
</body>
<script src="/js/i18n.js?webui-assets=`)
//line list.qtpl:72
	qw422016.N().S(cacheId)
//line list.qtpl:72
	qw422016.N().S(`"></script>

</html>
`)
//line list.qtpl:75
}

//line list.qtpl:75
func WriteList(qq422016 qtio422016.Writer, cacheId string, paths []string, files []FileInfo, showDirSize bool) {
//line list.qtpl:75
	qw422016 := qt422016.AcquireWriter(qq422016)
//line list.qtpl:75
	StreamList(qw422016, cacheId, paths, files, showDirSize)
//line list.qtpl:75
	qt422016.ReleaseWriter(qw422016)
//line list.qtpl:75
}

//line list.qtpl:75
func List(cacheId string, paths []string, files []FileInfo, showDirSize bool) string {
//line list.qtpl:75
	qb422016 := qt422016.AcquireByteBuffer()
//line list.qtpl:75
	WriteList(qb422016, cacheId, paths, files, showDirSize)
//line list.qtpl:75
	qs422016 := string(qb422016.B)
//line list.qtpl:75
	qt422016.ReleaseByteBuffer(qb422016)
//line list.qtpl:75
	return qs422016
//line list.qtpl:75
}
